package com.ebiz.mmt.dao;

import com.ebiz.mmt.domain.TaskPara;
import com.ebiz.ssi.dao.EntityDao;

/**
 * Code by AutoGenerated Builder
 * AutoGenerated Builder Version 2.1
 * @author Hui,Gang
 * @datetime 2011-11-14 10:15:03
 */
public interface TaskParaDao extends EntityDao<TaskPara> {

}