package com.ebiz.mmt.service;

import java.util.List;

import com.ebiz.mmt.domain.KonkaPeArticleUserMsg;

/**
 * Code by AutoGenerated Builder
 * AutoGenerated Builder Version 2.1
 * @author Hui,Gang
 * @datetime 2011-09-29 16:08:29
 */
public interface KonkaPeArticleUserMsgService {

	Long createKonkaPeArticleUserMsg(KonkaPeArticleUserMsg t);

	int modifyKonkaPeArticleUserMsg(KonkaPeArticleUserMsg t);

	int removeKonkaPeArticleUserMsg(KonkaPeArticleUserMsg t);

	KonkaPeArticleUserMsg getKonkaPeArticleUserMsg(KonkaPeArticleUserMsg t);

	List<KonkaPeArticleUserMsg> getKonkaPeArticleUserMsgList(KonkaPeArticleUserMsg t);

	Long getKonkaPeArticleUserMsgCount(KonkaPeArticleUserMsg t);

	List<KonkaPeArticleUserMsg> getKonkaPeArticleUserMsgPaginatedList(KonkaPeArticleUserMsg t);

}