package com.ebiz.mmt.dao.ibatis;

import java.util.HashMap;
import java.util.List;

import org.springframework.stereotype.Repository;

import com.ebiz.ssi.dao.ibatis.EntityDaoSqlMapImpl;
import com.ebiz.mmt.dao.KonkaPeAttachmentsDao;
import com.ebiz.mmt.domain.KonkaPeAttachments;

/**
 * Code by AutoGenerated Builder
 * AutoGenerated Builder Version 2.1
 * @author Hui,Gang
 * @datetime 2011-09-29 16:08:29
 */
@Repository
public class KonkaPeAttachmentsDaoSqlMapImpl extends EntityDaoSqlMapImpl<KonkaPeAttachments> implements KonkaPeAttachmentsDao {

	@Override
	public List<HashMap> selectKonkaPeAttachmentsMap(KonkaPeAttachments t) {
		
		return super.getSqlMapClientTemplate().queryForList("selectKonkaPeAttachmentsMap", t);
	}

}