package com.ebiz.mmt.dao;

import java.util.HashMap;
import java.util.List;

import com.ebiz.mmt.domain.KonkaPeAttachments;
import com.ebiz.ssi.dao.EntityDao;

/**
 * Code by AutoGenerated Builder
 * AutoGenerated Builder Version 2.1
 * @author Hui,Gang
 * @datetime 2011-09-29 17:05:13
 */
public interface KonkaPeAttachmentsDao extends EntityDao<KonkaPeAttachments> {
	
	List<HashMap> selectKonkaPeAttachmentsMap(KonkaPeAttachments t);
}