package com.ebiz.mmt.service.impl;

import java.util.List;

import javax.annotation.Resource;

import org.springframework.stereotype.Service;

import com.ebiz.mmt.dao.ImportDataTypesDao;
import com.ebiz.mmt.domain.ImportDataTypes;
import com.ebiz.mmt.service.ImportDataTypesService;

/**
 * Code by AutoGenerated Builder
 * AutoGenerated Builder Version 2.1
 * @author Hui,Gang
 * @datetime 2011-11-14 10:15:03
 */
 @Service
public class ImportDataTypesServiceImpl implements ImportDataTypesService {
	
	@Resource
	private ImportDataTypesDao importDataTypesDao;

	public Long createImportDataTypes(ImportDataTypes t) {
		return this.importDataTypesDao.insertEntity(t);
	}

	public ImportDataTypes getImportDataTypes(ImportDataTypes t) {
		return this.importDataTypesDao.selectEntity(t);
	}

	public Long getImportDataTypesCount(ImportDataTypes t) {
		return this.importDataTypesDao.selectEntityCount(t);
	}

	public List<ImportDataTypes> getImportDataTypesList(ImportDataTypes t) {
		return this.importDataTypesDao.selectEntityList(t);
	}

	public int modifyImportDataTypes(ImportDataTypes t) {
		return this.importDataTypesDao.updateEntity(t);
	}

	public int removeImportDataTypes(ImportDataTypes t) {
		return this.importDataTypesDao.deleteEntity(t);
	}

	public List<ImportDataTypes> getImportDataTypesPaginatedList(ImportDataTypes t) {
		return this.importDataTypesDao.selectEntityPaginatedList(t);
	}	

}