package com.ebiz.mmt.service;

import java.util.List;

import com.ebiz.mmt.domain.KonkaPePublicScope;

/**
 * Code by AutoGenerated Builder
 * AutoGenerated Builder Version 2.1
 * @author Hui,Gang
 * @datetime 2011-10-11 19:37:19
 */
public interface KonkaPePublicScopeService {

	Long createKonkaPePublicScope(KonkaPePublicScope t);

	int modifyKonkaPePublicScope(KonkaPePublicScope t);

	int removeKonkaPePublicScope(KonkaPePublicScope t);

	KonkaPePublicScope getKonkaPePublicScope(KonkaPePublicScope t);

	List<KonkaPePublicScope> getKonkaPePublicScopeList(KonkaPePublicScope t);

	Long getKonkaPePublicScopeCount(KonkaPePublicScope t);

	List<KonkaPePublicScope> getKonkaPePublicScopePaginatedList(KonkaPePublicScope t);

}