package com.ebiz.mmt.domain;

import java.io.Serializable;
import java.util.Date;

import org.apache.commons.lang.builder.ReflectionToStringBuilder;
import org.apache.commons.lang.builder.ToStringStyle;

import com.ebiz.ssi.domain.BaseDomain;

/**
 * Code by AutoGenerated Builder
 * AutoGenerated Builder Version 2.1
 * @author Hui,Gang
 * @datetime 2011-09-29 17:05:13
 */
 public class KonkaPeArticleUserMsg extends BaseDomain implements Serializable {
 	
 	private static final long serialVersionUID = -1L;

	/**
	 * ID
	 */
    private Long id;
           
	/**
	 * 文章ID
	 */
    private Long article_id;
           
	/**
	 * 生产企业ID
	 */
    private Long prod_entp_id;
           
	/**
	 * 留言内容
	 */
    private String msg_contents;
           
	/**
	 * 留言时间
	 */
    private Date msg_date;
           
	/**
	 * 是否匿名：0-否，1-是
	 */
    private Long is_anony;
           
	/**
	 * 用户IP
	 */
    private String user_ip;
           
	/**
	 * 留言人
	 */
    private Long user_id;
           
	/**
	 * 留言用户名
	 */
    private String user_name;
           
	public KonkaPeArticleUserMsg() {

	}
 
 	public void setId(Long id) {
		this.id = id;
	}
	
	public Long getId() {
		return id;
	}
           
 	public void setArticle_id(Long article_id) {
		this.article_id = article_id;
	}
	
	public Long getArticle_id() {
		return article_id;
	}
           
 	public void setProd_entp_id(Long prod_entp_id) {
		this.prod_entp_id = prod_entp_id;
	}
	
	public Long getProd_entp_id() {
		return prod_entp_id;
	}
           
 	public void setMsg_contents(String msg_contents) {
		this.msg_contents = msg_contents;
	}
	
	public String getMsg_contents() {
		return msg_contents;
	}
           
 	public void setMsg_date(Date msg_date) {
		this.msg_date = msg_date;
	}
	
	public Date getMsg_date() {
		return msg_date;
	}
           
 	public void setIs_anony(Long is_anony) {
		this.is_anony = is_anony;
	}
	
	public Long getIs_anony() {
		return is_anony;
	}
           
 	public void setUser_ip(String user_ip) {
		this.user_ip = user_ip;
	}
	
	public String getUser_ip() {
		return user_ip;
	}
           
 	public void setUser_id(Long user_id) {
		this.user_id = user_id;
	}
	
	public Long getUser_id() {
		return user_id;
	}
           
 	public void setUser_name(String user_name) {
		this.user_name = user_name;
	}
	
	public String getUser_name() {
		return user_name;
	}
           
	@Override 
    public String toString() { 
   		return ReflectionToStringBuilder.toString(this, ToStringStyle.MULTI_LINE_STYLE);
    }
    
 }