package com.ebiz.mmt.service.impl;

import java.util.List;

import javax.annotation.Resource;

import org.springframework.stereotype.Service;

import com.ebiz.mmt.dao.KonkaR3BackmoneyDao;
import com.ebiz.mmt.domain.KonkaR3Backmoney;
import com.ebiz.mmt.service.KonkaR3BackmoneyService;

/**
 * Code by AutoGenerated Builder AutoGenerated Builder Version 2.1
 * 
 * @author Hui,Gang
 * @datetime 2011-11-10 15:33:16
 */
@Service
public class KonkaR3BackmoneyServiceImpl implements KonkaR3BackmoneyService {

	@Resource
	private KonkaR3BackmoneyDao konkaR3BackmoneyDao;

	public Long createKonkaR3Backmoney(KonkaR3Backmoney t) {
		return this.konkaR3BackmoneyDao.insertEntity(t);
	}

	public KonkaR3Backmoney getKonkaR3Backmoney(KonkaR3Backmoney t) {
		return this.konkaR3BackmoneyDao.selectEntity(t);
	}

	public Long getKonkaR3BackmoneyCount(KonkaR3Backmoney t) {
		return this.konkaR3BackmoneyDao.selectEntityCount(t);
	}

	public List<KonkaR3Backmoney> getKonkaR3BackmoneyList(KonkaR3Backmoney t) {
		return this.konkaR3BackmoneyDao.selectEntityList(t);
	}

	public int modifyKonkaR3Backmoney(KonkaR3Backmoney t) {
		return this.konkaR3BackmoneyDao.updateEntity(t);
	}

	public int removeKonkaR3Backmoney(KonkaR3Backmoney t) {
		return this.konkaR3BackmoneyDao.deleteEntity(t);
	}

	public List<KonkaR3Backmoney> getKonkaR3BackmoneyPaginatedList(KonkaR3Backmoney t) {
		return this.konkaR3BackmoneyDao.selectEntityPaginatedList(t);
	}

	/**
	 * @author Hu,hao
	 * @version 2013-07-05
	 */
	public List<KonkaR3Backmoney> getKonkaR3BackmoneyListForTb(KonkaR3Backmoney t) {
		return this.konkaR3BackmoneyDao.selectKonkaR3BackmoneyListForTb(t);
	}

	/**
	 * @author Hu,Hao
	 * @version 2013-07-05
	 */
	public Long modifyKonkaR3BackmoneyForTb(List<KonkaR3Backmoney> t) {
		Long i = 0L;
		if (t.size() > 0) {
			for (KonkaR3Backmoney temp : t) {
				i++;
				KonkaR3Backmoney entity = new KonkaR3Backmoney();
				entity.setYear(temp.getYear());
				entity.setR3_code(temp.getR3_code());
				List<KonkaR3Backmoney> entityList = this.konkaR3BackmoneyDao.selectKonkaR3BackmoneyListForTb(entity);
				if (entityList.size() > 0) {// 更新
					temp.setId(entityList.get(0).getId());
					this.konkaR3BackmoneyDao.updateEntity(temp);
				} else {
					this.konkaR3BackmoneyDao.insertEntity(temp);// 新增
				}
			}
		}

		return i;
	}

	/**
	 * @author Hu,Hao
	 * @version 2013-09-13
	 */
	public List<KonkaR3Backmoney> getKonkaR3BackmoneyForMonth(KonkaR3Backmoney t) {
		return this.konkaR3BackmoneyDao.selectKonkaR3BackmoneyForMonth(t);
	}

	public List<KonkaR3Backmoney> getKonkaR3BackmoneyListForHkJd(KonkaR3Backmoney t) {
		return this.konkaR3BackmoneyDao.selectKonkaR3BackmoneyListForHkJd(t);
	}

	/**
	 * @author Hu,hao
	 * @version 2013-10-11
	 * @desc 根据用户的数据权限查询R3回款信息
	 */
	public Long getKonkaR3BackmoneyForRoleDataCount(KonkaR3Backmoney t) {
		return this.konkaR3BackmoneyDao.selectKonkaR3BackmoneyForRoleDataCount(t);
	}

	/**
	 * @author Hu,hao
	 * @version 2013-10-11
	 * @desc 根据用户的数据权限查询R3回款信息
	 */
	public List<KonkaR3Backmoney> getKonkaR3BackmoneyForRoleDataPaginatedList(KonkaR3Backmoney t) {
		return this.konkaR3BackmoneyDao.selectKonkaR3BackmoneyForRoleDataPaginatedList(t);
	}

	/**
	 * @author Hu,hao
	 * @version 2013-11-06
	 * @desc 回款数据
	 */
	public List<KonkaR3Backmoney> getKonkaR3BackmoneyFoHkDataPaginatedList(KonkaR3Backmoney t) {
		return this.konkaR3BackmoneyDao.selectKonkaR3BackmoneyFoHkDataPaginatedList(t);
	}

	/**
	 * @author Hu,hao
	 * @version 2013-11-06
	 * @desc 零售数据
	 */
	public List<KonkaR3Backmoney> getKonkaR3BackmoneyFoSailDataPaginatedList(KonkaR3Backmoney t) {
		return this.konkaR3BackmoneyDao.selectKonkaR3BackmoneyFoSailDataPaginatedList(t);
	}

	/**
	 * @author Hu,hao
	 * @version 2013-11-06
	 * @desc 结算数据
	 */
	public List<KonkaR3Backmoney> getKonkaR3BackmoneyFoJsDataPaginatedList(KonkaR3Backmoney t) {
		return this.konkaR3BackmoneyDao.selectKonkaR3BackmoneyFoJsDataPaginatedList(t);
	}

	/**
	 * @author Hu,hao
	 * @version 2013-11-06
	 * @desc 结算数据
	 */
	public List<KonkaR3Backmoney> getKonkaR3BackmoneyFoRwDataPaginatedList(KonkaR3Backmoney t) {
		return this.konkaR3BackmoneyDao.selectKonkaR3BackmoneyFoRwDataPaginatedList(t);
	}

	/**
	 * @author Hu,hao
	 * @version 2013-12-05
	 * @desc 首页展示数据
	 */
	public List<KonkaR3Backmoney> getKonkaR3SailAndJsDataToIndexPaginatedList(KonkaR3Backmoney t) {
		return this.konkaR3BackmoneyDao.selectKonkaR3SailAndJsDataToIndexPaginatedList(t);
	}

}