package com.ebiz.mmt.service;

import java.util.List;

import com.ebiz.mmt.domain.KonkaPeArticleContent;

/**
 * Code by AutoGenerated Builder
 * AutoGenerated Builder Version 2.1
 * @author Hui,Gang
 * @datetime 2011-09-29 16:08:29
 */
public interface KonkaPeArticleContentService {

	Long createKonkaPeArticleContent(KonkaPeArticleContent t);

	int modifyKonkaPeArticleContent(KonkaPeArticleContent t);

	int removeKonkaPeArticleContent(KonkaPeArticleContent t);

	KonkaPeArticleContent getKonkaPeArticleContent(KonkaPeArticleContent t);

	List<KonkaPeArticleContent> getKonkaPeArticleContentList(KonkaPeArticleContent t);

	Long getKonkaPeArticleContentCount(KonkaPeArticleContent t);

	List<KonkaPeArticleContent> getKonkaPeArticleContentPaginatedList(KonkaPeArticleContent t);

}