package com.ebiz.mmt.dao.ibatis;

import java.util.List;

import org.springframework.dao.DataAccessException;
import org.springframework.stereotype.Repository;

import com.ebiz.mmt.dao.MmtEntpShopDao;
import com.ebiz.mmt.domain.MmtEntpShop;
import com.ebiz.ssi.dao.ibatis.EntityDaoSqlMapImpl;

/**
 * Code by AutoGenerated Builder AutoGenerated Builder Version 2.1
 * 
 * @author Hui,Gang
 * @datetime 2011-09-29 15:54:30
 */
@Repository
public class MmtEntpShopDaoSqlMapImpl extends EntityDaoSqlMapImpl<MmtEntpShop> implements MmtEntpShopDao {

	@SuppressWarnings("unchecked")
	public List<MmtEntpShop> selectMmtEntpShopPaginatedListForSelect(MmtEntpShop t) throws DataAccessException {
		return super.getSqlMapClientTemplate().queryForList("selectMmtEntpShopPaginatedListForSelect", t);
	}

	@Override
	public Long selectMmtEntpShopNotRepeatCount(MmtEntpShop t) {
		return (Long) super.getSqlMapClientTemplate().queryForObject("selectMmtEntpShopNotRepeatCount", t);
	}

	@Override
	public Long selectMmtEntpShop2Count(MmtEntpShop t) {
		return (Long) super.getSqlMapClientTemplate().queryForObject("selectMmtEntpShop2Count", t);
	}

	@SuppressWarnings("unchecked")
	@Override
	public List<MmtEntpShop> selectMmtEntpShopNotRepeatPaginatedList(MmtEntpShop t) throws DataAccessException {
		return super.getSqlMapClientTemplate().queryForList("selectMmtEntpShopNotRepeatPaginatedList", t);
	}
}