package com.ebiz.mmt.domain;

import java.io.Serializable;
import java.util.Date;

import org.apache.commons.lang.builder.ReflectionToStringBuilder;
import org.apache.commons.lang.builder.ToStringStyle;

import com.ebiz.ssi.domain.BaseDomain;

/**
 * Code by AutoGenerated Builder
 * AutoGenerated Builder Version 2.1
 * @author Hui,Gang
 * @datetime 2011-10-10 17:03:47
 */
 public class KonkaDeptPdLink extends BaseDomain implements Serializable {
 	
 	private static final long serialVersionUID = -1L;

	/**
	 * ID
	 */
    private Long id;
           
	/**
	 * 部门ID
	 */
    private Long dept_id;
           
	/**
	 * 产品型号ID
	 */
    private Long pd_id;
           
	/**
	 * 添加人ID
	 */
    private Long add_user_id;
           
	/**
	 * 添加时间
	 */
    private Date add_date;
    
    private Long cls_id;
    
    private Long par_cls_id;
           
	public KonkaDeptPdLink() {

	}
 
 	public void setId(Long id) {
		this.id = id;
	}
	
	public Long getId() {
		return id;
	}
           
 	public void setDept_id(Long dept_id) {
		this.dept_id = dept_id;
	}
	
	public Long getDept_id() {
		return dept_id;
	}
           
 	public void setPd_id(Long pd_id) {
		this.pd_id = pd_id;
	}
	
	public Long getPd_id() {
		return pd_id;
	}
           
 	public void setAdd_user_id(Long add_user_id) {
		this.add_user_id = add_user_id;
	}
	
	public Long getAdd_user_id() {
		return add_user_id;
	}
           
 	public void setAdd_date(Date add_date) {
		this.add_date = add_date;
	}
	
	public Date getAdd_date() {
		return add_date;
	}
	
	
           
	public Long getCls_id() {
		return cls_id;
	}

	public void setCls_id(Long cls_id) {
		this.cls_id = cls_id;
	}

	public Long getPar_cls_id() {
		return par_cls_id;
	}

	public void setPar_cls_id(Long par_cls_id) {
		this.par_cls_id = par_cls_id;
	}

	@Override 
    public String toString() { 
   		return ReflectionToStringBuilder.toString(this, ToStringStyle.MULTI_LINE_STYLE);
    }
    
 }