package com.ebiz.mmt.dao.ibatis;

import org.springframework.stereotype.Repository;

import com.ebiz.ssi.dao.ibatis.EntityDaoSqlMapImpl;
import com.ebiz.mmt.dao.KonkaPeArticleContentDao;
import com.ebiz.mmt.domain.KonkaPeArticleContent;

/**
 * Code by AutoGenerated Builder
 * AutoGenerated Builder Version 2.1
 * @author Hui,Gang
 * @datetime 2011-09-29 16:08:29
 */
@Repository
public class KonkaPeArticleContentDaoSqlMapImpl extends EntityDaoSqlMapImpl<KonkaPeArticleContent> implements KonkaPeArticleContentDao {

}