package com.ebiz.mmt.domain;

import java.io.Serializable;
import java.util.List;

import org.apache.commons.lang.builder.ReflectionToStringBuilder;
import org.apache.commons.lang.builder.ToStringStyle;

import com.ebiz.ssi.domain.BaseDomain;

/**
 * Code by AutoGenerated Builder
 * AutoGenerated Builder Version 2.1
 * @author Hui,Gang
 * @datetime 2011-11-14 10:15:02
 */
 public class ImportDataTypes extends BaseDomain implements Serializable {
 	
 	private static final long serialVersionUID = -1L;

	/**
	 * ID
	 */
    private Long id;
           
	/**
	 * 父ID<br />
顶级为0
	 */
    private Integer par_id;
           
	/**
	 * 数据类别<br />
暂定：<br />
1：单客户，此种类别去R3表中查相关数据<br />
2：客户群<br />
3：分公司，此种类别去组织架构表中查相关数据<br />
4：分大区

	 */
    private Long data_type;
           
	/**
	 * 类别名称
	 */
    private String type_name;
           
	/**
	 * 排序值
	 */
    private Long order_value;
    
    private List<TaskPara> taskParaList;
           
	public List<TaskPara> getTaskParaList() {
		return taskParaList;
	}

	public void setTaskParaList(List<TaskPara> taskParaList) {
		this.taskParaList = taskParaList;
	}

	public ImportDataTypes() {

	}
 
 	public void setId(Long id) {
		this.id = id;
	}
	
	public Long getId() {
		return id;
	}
           
 	public void setPar_id(Integer par_id) {
		this.par_id = par_id;
	}
	
	public Integer getPar_id() {
		return par_id;
	}
           
 	public void setData_type(Long data_type) {
		this.data_type = data_type;
	}
	
	public Long getData_type() {
		return data_type;
	}
           
 	public void setType_name(String type_name) {
		this.type_name = type_name;
	}
	
	public String getType_name() {
		return type_name;
	}
           
 	public void setOrder_value(Long order_value) {
		this.order_value = order_value;
	}
	
	public Long getOrder_value() {
		return order_value;
	}
           
	@Override 
    public String toString() { 
   		return ReflectionToStringBuilder.toString(this, ToStringStyle.MULTI_LINE_STYLE);
    }

	
    
 }