package com.ebiz.mmt.service;

import java.util.List;

import com.ebiz.mmt.domain.KonkaPeArticleInfo;

/**
 * Code by AutoGenerated Builder AutoGenerated Builder Version 2.1
 * 
 * @author Hui,Gang
 * @datetime 2011-09-29 17:05:13
 */
public interface KonkaPeArticleInfoService {

	Long createKonkaPeArticleInfo(KonkaPeArticleInfo t);

	int modifyKonkaPeArticleInfo(KonkaPeArticleInfo t);

	int removeKonkaPeArticleInfo(KonkaPeArticleInfo t);

	KonkaPeArticleInfo getKonkaPeArticleInfo(KonkaPeArticleInfo t);

	List<KonkaPeArticleInfo> getKonkaPeArticleInfoList(KonkaPeArticleInfo t);

	Long getKonkaPeArticleInfoCount(KonkaPeArticleInfo t);

	List<KonkaPeArticleInfo> getKonkaPeArticleInfoPaginatedList(KonkaPeArticleInfo t);

	// 新增加盟信息
	Long createKonkaPeArticleInfoForJoinInfo(KonkaPeArticleInfo t);

	// 修改加盟信息
	int modifyKonkaPeArticleInfoForJoinInfo(KonkaPeArticleInfo t);

	Long getKonkaPeArticleInfoCountForReceive(KonkaPeArticleInfo t);

	List<KonkaPeArticleInfo> getKonkaPeArticleInfoPaginatedListForReceive(KonkaPeArticleInfo t);

	/**
	 * @author Hu,Hao
	 * @version 2013-05-30
	 */
	List<KonkaPeArticleInfo> getKonkaPeArticleInfoForMobilePaginatedList(KonkaPeArticleInfo t);
	
	/**
	 * @author Hu,Hao
	 * @version 2013-05-30
	 */
	Long getKonkaPeArticleInfoForMobileCount(KonkaPeArticleInfo t);
	
	/**
	 * @author Hu,Hao
	 * @version 2013-07-14
	 */
	List<KonkaPeArticleInfo> getKonkaPeArticleInfoForGroupPaginatedList(KonkaPeArticleInfo t);
	
	/**
	 * @author Hu,Hao
	 * @version 2013-07-14
	 */
	void createKonkaPeArticleInfoForGroup(KonkaPeArticleInfo t);
	
	/**
	 * @author Hu,Hao
	 * @version 2013-07-14
	 */
	void modifyKonkaPeArticleInfoForGroup(KonkaPeArticleInfo t);
	
}