package com.ebiz.mmt.dao;

import com.ebiz.mmt.domain.ChannelDataImport;
import com.ebiz.ssi.dao.EntityDao;
import org.springframework.dao.DataAccessException;

import java.math.BigDecimal;
import java.sql.SQLException;
import java.util.Date;
import java.util.HashMap;
import java.util.List;

/**
 * Code by AutoGenerated Builder AutoGenerated Builder Version 2.1
 * 
 * @author Hui,Gang
 * @datetime 2011-11-07 15:52:25
 */
public interface ChannelDataImportDao extends EntityDao<ChannelDataImport> {

	/**
	 * @author Wang,Yang
	 * @version 2011-11-10
	 */
	public abstract java.math.BigDecimal selectChannelDataSumByPdId(ChannelDataImport t) throws DataAccessException;

	public List<ChannelDataImport> selectChannelDataImportListToSum(ChannelDataImport t) throws DataAccessException;

	public abstract List<ChannelDataImport> selectChannelDataImportPaginatedListForStat(ChannelDataImport t);

	public abstract List<ChannelDataImport> selectChannelDataImportPaginatedListForModel(ChannelDataImport t);

	public List<ChannelDataImport> selectChannelDataListByPdId(ChannelDataImport cd);

	Long selectChannelDataImportForSum(ChannelDataImport cd) throws DataAccessException;

	public abstract List<ChannelDataImport> selectChannelDataImportListForStatistics(ChannelDataImport t);

	public HashMap<BigDecimal, BigDecimal> selectChannelDataImportAllCountAndAllMoney(ChannelDataImport t);

	public Date selectTheMaxImportDate(ChannelDataImport t);

	/**
	 * @author ZHOU
	 * @param list
	 * @return
	 * @throws SQLException
	 */
	public void insertChannelDataImportBatch(List<ChannelDataImport> list) throws SQLException;

	/**
	 * @author Hu,Hao
	 * @version 2013-09-14
	 * @desc 分公司业绩排名
	 */
	List<ChannelDataImport> selectChannelDataImportForFgsTop(ChannelDataImport t) throws DataAccessException;

	/**
	 * @author Hu,Hao
	 * @version 2013-09-15
	 * @desc 经办业绩排名
	 */
	List<ChannelDataImport> selectChannelDataImportForJybTop(ChannelDataImport t);
	
	/**
	 * @author Hu,Hao
	 * @version 2013-09-22
	 * @desc 任务完成分析
	 */
	List<ChannelDataImport> selectChannelDataImportListToMonth(ChannelDataImport t);
	/**
	 * @author Hu,Hao
	 * @version 2013-09-22
	 * @desc 任务完成分析
	 */
	List<ChannelDataImport> selectChannelDataImportListToSeason(ChannelDataImport t);
	
	/**
	 * @author Hu,Hao
	 * @version 2013-09-22
	 * @desc 任务完成分析
	 */
	List<ChannelDataImport> selectChannelDataImportListToAll(ChannelDataImport t);
	
	/**
	 * @author Hu,Hao
	 * @version 2013-11-14
	 * @desc 分公司业绩排名（回款）
	 */
	List<ChannelDataImport> selectChannelDataImportForFgsHkTop(ChannelDataImport t);
	
	/**
	 * @author Hu,Hao
	 * @version 2013-12-18
	 * @desc 分公司业绩排名（其他）
	 */
	List<ChannelDataImport> selectChannelDataImportForFgsHkQt(ChannelDataImport t);
	
	/**
	 * @author Xing,XiuDong
	 * @version 2013-12-23
	 */
	List<ChannelDataImport> selectGroupByPdStatList(ChannelDataImport t);
	/**
	 * 查r3客户是否有 结算
	 * @param cd
	 * @return
	 * @throws DataAccessException
	 */
	Long selectR3codeIsJs(ChannelDataImport cd) throws DataAccessException;

	List<ChannelDataImport> selectChannelDataImportListForFifo(ChannelDataImport channelDataImport);
}