package com.ebiz.mmt.service;

import java.math.BigDecimal;
import java.sql.SQLException;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Set;

import org.springframework.dao.DataAccessException;

import com.ebiz.mmt.domain.ChannelDataImport;

/**
 * Code by AutoGenerated Builder AutoGenerated Builder Version 2.1
 * 
 * @author Hui,Gang
 * @datetime 2011-11-07 15:52:25
 */
public interface ChannelDataImportService {

	Long createChannelDataImport(ChannelDataImport t);

	int modifyChannelDataImport(ChannelDataImport t);

	int removeChannelDataImport(ChannelDataImport t);

	ChannelDataImport getChannelDataImport(ChannelDataImport t);

	List<ChannelDataImport> getChannelDataImportList(ChannelDataImport t);

	Long getChannelDataImportCount(ChannelDataImport t);

	List<ChannelDataImport> getChannelDataImportPaginatedList(ChannelDataImport t);

	List<ChannelDataImport> getChannelDataImportPaginatedListForStat(ChannelDataImport t);

	List<ChannelDataImport> getChannelDataImportPaginatedListForModel(ChannelDataImport t);

	/**
	 * @author Wang,Yang
	 * @version 2011-11-10
	 */
	java.math.BigDecimal getChannelDataSumByPdId(ChannelDataImport t);

	Long getChannelDataImportForSum(ChannelDataImport t);

	List<ChannelDataImport> getChannelDataListByPdId(ChannelDataImport t);

	/**
	 * 客户结算分析
	 * 
	 * @param t
	 * @return
	 */
	List<ChannelDataImport> getChannelDataImportListForStatistics(ChannelDataImport t);

	HashMap<BigDecimal, BigDecimal> getChannelDataImportAllCountAndAllMoney(ChannelDataImport t);
	
	void createChannelDataImportList(List<ChannelDataImport> t);

	void modifyChannelDataImportList(List<ChannelDataImport> t);
	
	/**
	 * @author ZHOU
	 * @return 取得最大的导入时间
	 */
	Date selectTheMaxImportDate(ChannelDataImport t);
	

	/**
	 * 此方法同步回来的数据可用于统计分公司与客户的订单,但此明细数据不包括KF交货单,物流交货单什么的
	 */
	HashMap<String, Long> createOrModifySyncChannelDataForfgsTj(Set<String> syncVkorgList, String v_vtweg,
			String v_spart, String v_audat_begin, String v_audat_end, String v_kunnr) throws SQLException;
	

	/**
	 * @author Hu,Hao
	 * @version 2013-09-14
	 * @desc 分公司业绩排名
	 */
	List<ChannelDataImport> getChannelDataImportForFgsTop(ChannelDataImport t);
	
	/**
	 * @author Hu,Hao
	 * @version 2013-09-15
	 * @desc 经办业绩排名
	 */
	List<ChannelDataImport> getChannelDataImportForJybTop(ChannelDataImport t);

	/**
	 * @author Hu,Hao
	 * @version 2013-09-22
	 * @desc 任务完成分析
	 */
	List<ChannelDataImport> getChannelDataImportListToMonth(ChannelDataImport t);
	/**
	 * @author Hu,Hao
	 * @version 2013-09-22
	 * @desc 任务完成分析
	 */
	List<ChannelDataImport> getChannelDataImportListToSeason(ChannelDataImport t);
	
	/**
	 * @author Hu,Hao
	 * @version 2013-09-22
	 * @desc 任务完成分析
	 */
	List<ChannelDataImport> getChannelDataImportListToAll(ChannelDataImport t);
	
	/**
	 * @author Hu,Hao
	 * @version 2013-11-14
	 * @desc 分公司业绩排名（回款）
	 */
	List<ChannelDataImport> getChannelDataImportForFgsHkTop(ChannelDataImport t);
	

	/**
	 * @author Hu,Hao
	 * @version 2013-12-18
	 * @desc 分公司业绩排名（其他）
	 */
	List<ChannelDataImport> getChannelDataImportForFgsHkQt(ChannelDataImport t);
	
	/**
	 * @author Xing,XiuDong
	 * @version 2013-12-23
	 */
	List<ChannelDataImport> getGroupByPdStatList(ChannelDataImport t);
	
	/**
	 * 查r3客户是否有 结算
	 * @param cd
	 * @return
	 * @throws DataAccessException
	 */
	Long getR3codeIsJs(ChannelDataImport cd);
}