package com.ebiz.mmt.service;

import java.util.List;

import com.ebiz.mmt.domain.ImportDataTypes;

/**
 * Code by AutoGenerated Builder
 * AutoGenerated Builder Version 2.1
 * @author Hui,Gang
 * @datetime 2011-11-14 10:15:03
 */
public interface ImportDataTypesService {

	Long createImportDataTypes(ImportDataTypes t);

	int modifyImportDataTypes(ImportDataTypes t);

	int removeImportDataTypes(ImportDataTypes t);

	ImportDataTypes getImportDataTypes(ImportDataTypes t);

	List<ImportDataTypes> getImportDataTypesList(ImportDataTypes t);

	Long getImportDataTypesCount(ImportDataTypes t);

	List<ImportDataTypes> getImportDataTypesPaginatedList(ImportDataTypes t);

}