package com.ebiz.mmt.service;

import java.util.List;

import com.ebiz.mmt.domain.KonkaPeArticleType;

/**
 * Code by AutoGenerated Builder
 * AutoGenerated Builder Version 2.1
 * @author Hui,Gang
 * @datetime 2011-09-28 18:29:21
 */
public interface KonkaPeArticleTypeService {

	Long createKonkaPeArticleType(KonkaPeArticleType t);

	int modifyKonkaPeArticleType(KonkaPeArticleType t);

	int removeKonkaPeArticleType(KonkaPeArticleType t);

	KonkaPeArticleType getKonkaPeArticleType(KonkaPeArticleType t);

	List<KonkaPeArticleType> getKonkaPeArticleTypeList(KonkaPeArticleType t);

	Long getKonkaPeArticleTypeCount(KonkaPeArticleType t);

	List<KonkaPeArticleType> getKonkaPeArticleTypePaginatedList(KonkaPeArticleType t);

}