package com.ebiz.mmt.service;

import java.util.List;

import com.ebiz.mmt.domain.KonkaR3Backmoney;

/**
 * Code by AutoGenerated Builder AutoGenerated Builder Version 2.1
 * 
 * @author Hui,Gang
 * @datetime 2011-11-10 15:33:16
 */
public interface KonkaR3BackmoneyService {

	Long createKonkaR3Backmoney(KonkaR3Backmoney t);

	int modifyKonkaR3Backmoney(KonkaR3Backmoney t);

	int removeKonkaR3Backmoney(KonkaR3Backmoney t);

	KonkaR3Backmoney getKonkaR3Backmoney(KonkaR3Backmoney t);

	List<KonkaR3Backmoney> getKonkaR3BackmoneyList(KonkaR3Backmoney t);

	Long getKonkaR3BackmoneyCount(KonkaR3Backmoney t);

	List<KonkaR3Backmoney> getKonkaR3BackmoneyPaginatedList(KonkaR3Backmoney t);

	/**
	 * @author Hu,hao
	 * @version 2013-07-05
	 */
	List<KonkaR3Backmoney> getKonkaR3BackmoneyListForTb(KonkaR3Backmoney t);

	/**
	 * @author Hu,Hao
	 * @version 2013-07-05
	 */
	Long modifyKonkaR3BackmoneyForTb(List<KonkaR3Backmoney> t);

	/**
	 * @author Hu,Hao
	 * @version 2013-09-13
	 */
	List<KonkaR3Backmoney> getKonkaR3BackmoneyForMonth(KonkaR3Backmoney t);

	/**
	 * @author Hu,hao
	 * @version 2013-09-17
	 */
	List<KonkaR3Backmoney> getKonkaR3BackmoneyListForHkJd(KonkaR3Backmoney t);
	
	/**
	 * @author Hu,hao
	 * @version 2013-10-11
	 * @desc 根据用户的数据权限查询R3回款信息
	 */
	Long getKonkaR3BackmoneyForRoleDataCount(KonkaR3Backmoney t);
	
	/**
	 * @author Hu,hao
	 * @version 2013-10-11
	 * @desc 根据用户的数据权限查询R3回款信息
	 */
	List<KonkaR3Backmoney> getKonkaR3BackmoneyForRoleDataPaginatedList(KonkaR3Backmoney t);

	/**
	 * @author Hu,hao
	 * @version 2013-11-06
	 * @desc 回款数据
	 */
	List<KonkaR3Backmoney> getKonkaR3BackmoneyFoHkDataPaginatedList(KonkaR3Backmoney t);
	
	/**
	 * @author Hu,hao
	 * @version 2013-11-06
	 * @desc 零售数据
	 */
	List<KonkaR3Backmoney> getKonkaR3BackmoneyFoSailDataPaginatedList(KonkaR3Backmoney t);
	
	/**
	 * @author Hu,hao
	 * @version 2013-11-06
	 * @desc 结算数据
	 */
	List<KonkaR3Backmoney> getKonkaR3BackmoneyFoJsDataPaginatedList(KonkaR3Backmoney t);
	
	/**
	 * @author Hu,hao
	 * @version 2013-11-06
	 * @desc 结算数据
	 */
	List<KonkaR3Backmoney> getKonkaR3BackmoneyFoRwDataPaginatedList(KonkaR3Backmoney t);
	
	/**
	 * @author Hu,hao
	 * @version 2013-12-05
	 * @desc 首页展示数据
	 */
	List<KonkaR3Backmoney> getKonkaR3SailAndJsDataToIndexPaginatedList(KonkaR3Backmoney t);
}