package com.ebiz.mmt.service;

import java.util.List;

import com.ebiz.mmt.domain.KonkaDeptPdLink;

/**
 * Code by AutoGenerated Builder
 * AutoGenerated Builder Version 2.1
 * @author Hui,Gang
 * @datetime 2011-10-10 17:03:48
 */
public interface KonkaDeptPdLinkService {

	Long createKonkaDeptPdLink(KonkaDeptPdLink t);

	int modifyKonkaDeptPdLink(KonkaDeptPdLink t);

	int removeKonkaDeptPdLink(KonkaDeptPdLink t);

	KonkaDeptPdLink getKonkaDeptPdLink(KonkaDeptPdLink t);

	List<KonkaDeptPdLink> getKonkaDeptPdLinkList(KonkaDeptPdLink t);

	Long getKonkaDeptPdLinkCount(KonkaDeptPdLink t);

	List<KonkaDeptPdLink> getKonkaDeptPdLinkPaginatedList(KonkaDeptPdLink t);
	
	/**
	 * @author  wangyang
	 * @param t
	 * @param pd_ids
	 * @return Long
	 * @datetime 2012-04-16 11:47:48
	 */
	void createKonkaDeptPdLinkAndClean(KonkaDeptPdLink t,String pd_ids);

}