package com.sf.integration.warehouse;

public class Temp {

	private String shop_name = "";// 商家店铺名称 shop_name
	private String erp_order = "";// 订单号码 erp_order
	private String order_type = "";// 订单类型 order_type
	private String order_date = "";// 下单日期 order_date
	private String ship_from_name = "";// 寄件公司 ship_from_name
	private String ship_from_attention_to = "";// 寄件人 ship_from_attention_to
	private String ship_from_country = "";// 寄件国家或地区 ship_from_country
	private String ship_from_province = "";// 寄件省 ship_from_province
	private String ship_from_city = "";// 寄件市 ship_from_city
	private String ship_from_area = "";// 寄件区/县 ship_from_area
	private String ship_from_address = "";// 寄件地址 ship_from_address
	private String ship_from_postal_code = "";// 寄件邮编 ship_from_postal_code
	private String ship_from_phone_num = "";// 寄件手机 ship_from_phone_num
	private String ship_from_tel_num = "";// 寄件固定电话 ship_from_tel_num
	private String ship_from_email_address = "";// 寄件邮箱地址  ship_from_email_address
	private String ship_to_name = "";// 收件公司 ship_to_name
	private String ship_to_attention_to = "";// 收件人 ship_to_attention_to
	private String ship_to_country = "";// 收件国家或地区 ship_to_country
	private String ship_to_province = "";// 收件省 ship_to_province
	private String ship_to_city = "";// 收件市 ship_to_city
	private String ship_to_area = "";// 收件区/县 ship_to_area
	private String ship_to_address = "";// 收件地址 ship_to_address
	private String ship_to_postal_code = "";// 收件邮编 ship_to_postal_code
	private String ship_to_phone_num = "";// 收件手机 ship_to_phone_num
	private String ship_to_tel_num = "";// 收件固定电话 ship_to_tel_num
	private String ship_to_email_address = "";// 收件邮箱地址 ship_to_email_address
	private String carrier = "";// 承运商 carrier
	private String carrier_service = "";// 承运商服务类型 carrier_service
	private String route_numbers = "";// 路线编号 route_numbers
	private String packing_note = "";// 货品包装备注 packing_note
	private String complete_delivery = "";// 需整单发货 complete_delivery
	private String freight = "";// 运费 freight
	private String payment_of_charge = "";// 货主运费付款方式 payment_of_charge
	private String payment_district = "";// 付款地区：城市名称 payment_district
	private String cod = "";// 是否货到付款 cod
	private String amount = "";// 代收货款金额 amount
	private String self_pickup = "";// 是否上门自取 self_pickup
	private String value_insured = "";// 是否保价 value_insured
	private String declared_value = "";// 声明价值 declared_value
	private String return_receipt_service = "";// 签回单 return_receipt_service
	private String delivery_date = "";// 发货日期 delivery_date
	private String delivery_requested = "";// 配送要求 delivery_requested
	private String invoice = "";// 需要发票 invoice
	private String invoice_type = "";// 发票类型 invoice_type
	private String invoice_title = "";// 发票抬头 invoice_title
	private String invoice_content = "";// 发票内容 invoice_content
	private String order_note = "";// 订单备注 order_note
	private String company_note = "";// 商家备注 company_note
	private String priority = "";// 订单优先级 priority
	private String order_total_amount = "";// 订单总金额 order_total_amount
	private String order_discount = "";// 订单优惠金额 order_discount
	private String balance_amount = "";// 余额支付金额 balance_amount
	private String coupons_amount = "";// 优惠卷金额 coupons_amount
	private String gift_card_amount = "";// 礼品卡金额 gift_card_amount
	private String other_charge = "";// 其它金额 other_charge
	private String actual_amount = "";// 实际支付金额 actual_amount
	private String customer_payment_method = "";// 客户付款方式  customer_payment_method
	private String monthly_account = "";// 月结账号 monthly_account
	private String from_flag = "";// 寄件方标识 from_flag
	private String user_def1 = "";// 预留字段 1 user_def1
	private String user_def2 = "";// 预留字段2 user_def2
	private String user_def3 = "";// 预留字段3 user_def3
	private String user_def4 = "";// 预留字段4 user_def4
	private String user_def5 = "";// 预留字段5 user_def5
	private String user_def6 = "";// 预留字段6 user_def6
	private String user_def7 = "";// 预留字段 7 user_def7
	private String user_def8 = "";// 预留字段8 user_def8
	private String user_def9 = "";// 预留字段9 user_def9
	private String user_def10 = "";// 预留字段 10 user_def10
	private String user_def11 = "";// 预留字段 11 user_def11
	private String user_def12 = "";// 预留字段 12 user_def12
	private String user_def13 = "";// 预留字段 13 user_def13
	private String user_def14 = "";// 预留字段 14 user_def14
	private String user_def15 = "";// 预留字段 15 user_def15
	private String user_def16 = "";// 预留字段 16 user_def16
	private String user_def17 = "";// 预留字段 17 user_def17
	private String user_def18 = "";// 预留字段 18 user_def18
	private String user_def19 = "";// 预留字段 19 user_def19
	private String user_def20 = "";// 预留字段20 user_def20
}
