package com.ebiz.mmt.dao;

import com.ebiz.mmt.domain.KonkaPeArticleContent;
import com.ebiz.ssi.dao.EntityDao;

/**
 * Code by AutoGenerated Builder
 * AutoGenerated Builder Version 2.1
 * @author Hui,Gang
 * @datetime 2011-09-29 17:05:12
 */
public interface KonkaPeArticleContentDao extends EntityDao<KonkaPeArticleContent> {

}