package com.ebiz.mmt.service;

import java.util.HashMap;
import java.util.List;

import com.ebiz.mmt.domain.KonkaPeAttachments;

/**
 * Code by AutoGenerated Builder
 * AutoGenerated Builder Version 2.1
 * @author Hui,Gang
 * @datetime 2011-09-29 16:08:30
 */
public interface KonkaPeAttachmentsService {

	Long createKonkaPeAttachments(KonkaPeAttachments t);

	int modifyKonkaPeAttachments(KonkaPeAttachments t);

	int removeKonkaPeAttachments(KonkaPeAttachments t);

	KonkaPeAttachments getKonkaPeAttachments(KonkaPeAttachments t);

	List<KonkaPeAttachments> getKonkaPeAttachmentsList(KonkaPeAttachments t);

	Long getKonkaPeAttachmentsCount(KonkaPeAttachments t);

	List<KonkaPeAttachments> getKonkaPeAttachmentsPaginatedList(KonkaPeAttachments t);
	
	/**
	 * 返回附件MAP
	 * @author Angus
	 * @date 2014-8-5
	 * @param t
	 * @return
	 */
	List<HashMap> getKonkaPeAttachmentsMap(KonkaPeAttachments t);
}