package com.ebiz.mmt.domain;

import java.io.Serializable;

import org.apache.commons.lang.builder.ReflectionToStringBuilder;
import org.apache.commons.lang.builder.ToStringStyle;

import com.ebiz.ssi.domain.BaseDomain;

/**
 * Code by AutoGenerated Builder AutoGenerated Builder Version 2.1
 * 
 * @author Hui,Gang
 * @datetime 2011-10-11 19:37:18
 */
public class KonkaPePublicScope extends BaseDomain implements Serializable {

	private static final long serialVersionUID = -1L;

	/**
	 * ID
	 */
	private Long id;

	/**
	 * 资讯ID
	 */
	private Long article_id;

	/**
	 * 投放类别<br />
	 * 0：全部区域进行投放（只有admin与事业部有此功能）<br />
	 * 1：按地区进行投放，多个地区的话存多条记录<br />
	 * 2：按网点类别进行投放，多个网点类别的存多条记录<br />
	 * 3：对指定网点进行投放，多个网点存多条记录
	 */
	private Long public_type;

	/**
	 * 投放范围<br />
	 * 当PUBLIC_TYPE=0时该字段为空<br />
	 * 当PUBLIC_TYPE=1时存p_index<br />
	 * 当PUBLIC_TYPE=2时存网点类别ID<br />
	 * 当PUBLIC_TYPE=3时存网点ID
	 */
	private Long public_scope;

	private Integer public_target;

	public KonkaPePublicScope() {

	}

	public void setId(Long id) {
		this.id = id;
	}

	public Long getId() {
		return id;
	}

	public void setArticle_id(Long article_id) {
		this.article_id = article_id;
	}

	public Long getArticle_id() {
		return article_id;
	}

	public void setPublic_type(Long public_type) {
		this.public_type = public_type;
	}

	public Long getPublic_type() {
		return public_type;
	}

	public void setPublic_scope(Long public_scope) {
		this.public_scope = public_scope;
	}

	public Long getPublic_scope() {
		return public_scope;
	}

	public Integer getPublic_target() {
		return public_target;
	}

	public void setPublic_target(Integer public_target) {
		this.public_target = public_target;
	}

	@Override
	public String toString() {
		return ReflectionToStringBuilder.toString(this, ToStringStyle.MULTI_LINE_STYLE);
	}

}