package com.ebiz.mmt.domain;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

import org.apache.commons.lang.builder.ReflectionToStringBuilder;
import org.apache.commons.lang.builder.ToStringStyle;

import com.ebiz.ssi.domain.BaseDomain;

/**
 * Code by AutoGenerated Builder AutoGenerated Builder Version 2.1
 * 
 * @author Hui,Gang
 * @datetime 2011-12-01 09:21:55
 */
public class KonkaExpenseClaims extends BaseDomain implements Serializable {

	private static final long serialVersionUID = -1L;

	private Long file_id;

	/**
	 * 广告受益客户
	 */
	private String column_1;

	/**
	 * 受益客户本年度销售额
	 */
	private Long column_2;

	/**
	 * 受益客户本年度广告累计投入
	 */
	private Long c_type;

	/**
	 * 活动主题内容及预期效果(可附活动方案)<br />
	 * 可附件上传
	 */
	private String column_4;

	/**
	 * 广告费预算金额、数量、规格、制作内容（促销礼品申请注明明细）
	 */
	private String column_5;

	/**
	 * 费用总额：元
	 */
	private BigDecimal column_6;

	/**
	 * 物料制作广告公司
	 */
	private String column_7;

	/**
	 * 自批复日起制作、验收时间
	 */
	private Date column_8;

	/**
	 * 发货、运输、到达时间
	 */
	private Date column_9;
	
	private Long r3_shop_id;

	private KonkaoaFiles files;

	/**
	 * 提交人ID
	 */
	private Long submit_user_id;

	private Date submit_datetime;

	private String content;

	public String getContent() {
		return content;
	}

	public void setContent(String content) {
		this.content = content;
	}

	public KonkaExpenseClaims() {
	}

	public Date getSubmit_datetime() {
		return submit_datetime;
	}

	public void setSubmit_datetime(Date submit_datetime) {
		this.submit_datetime = submit_datetime;
	}

	public void setFile_id(Long file_id) {
		this.file_id = file_id;
	}

	public Long getFile_id() {
		return file_id;
	}

	public void setColumn_1(String column_1) {
		this.column_1 = column_1;
	}

	public String getColumn_1() {
		return column_1;
	}

	public void setColumn_2(Long column_2) {
		this.column_2 = column_2;
	}

	public Long getColumn_2() {
		return column_2;
	}

	public void setC_type(Long c_type) {
		this.c_type = c_type;
	}

	public Long getC_type() {
		return c_type;
	}

	public void setColumn_4(String column_4) {
		this.column_4 = column_4;
	}

	public String getColumn_4() {
		return column_4;
	}

	public void setColumn_5(String column_5) {
		this.column_5 = column_5;
	}

	public String getColumn_5() {
		return column_5;
	}

	public void setColumn_6(BigDecimal column_6) {
		this.column_6 = column_6;
	}

	public BigDecimal getColumn_6() {
		return column_6;
	}

	public void setColumn_7(String column_7) {
		this.column_7 = column_7;
	}

	public String getColumn_7() {
		return column_7;
	}

	public void setColumn_8(Date column_8) {
		this.column_8 = column_8;
	}

	public Date getColumn_8() {
		return column_8;
	}

	public void setColumn_9(Date column_9) {
		this.column_9 = column_9;
	}

	public Date getColumn_9() {
		return column_9;
	}

	public Long getR3_shop_id() {
		return r3_shop_id;
	}

	public void setR3_shop_id(Long r3_shop_id) {
		this.r3_shop_id = r3_shop_id;
	}
	
	public Long getSubmit_user_id() {
		return submit_user_id;
	}

	public void setSubmit_user_id(Long submit_user_id) {
		this.submit_user_id = submit_user_id;
	}

	public KonkaoaFiles getFiles() {
		return files;
	}

	public void setFiles(KonkaoaFiles files) {
		this.files = files;
	}

	@Override
	public String toString() {
		return ReflectionToStringBuilder.toString(this, ToStringStyle.MULTI_LINE_STYLE);
	}

}