package com.ebiz.mmt.domain;

import java.io.Serializable;
import java.util.Date;
import java.util.List;

import org.apache.commons.lang.builder.ReflectionToStringBuilder;
import org.apache.commons.lang.builder.ToStringStyle;

import com.ebiz.ssi.domain.BaseDomain;

/**
 * Code by AutoGenerated Builder AutoGenerated Builder Version 2.1
 * 
 * @author Hui,Gang
 * @datetime 2011-09-29 17:05:13
 */
public class KonkaPeArticleInfo extends BaseDomain implements Serializable {

	private static final long serialVersionUID = -1L;

	private Long id;

	/**
	 * 资讯标题
	 */
	private String title;

	/**
	 * 资讯短标题
	 */
	private String short_title;

	/**
	 * 关键字
	 */
	private String key_words;

	/**
	 * 资讯模块ID(SYS_MODULE中的MOD_ID)
	 */
	private Long article_mod_id;

	/**
	 * 资讯类别ID
	 */
	private Long article_type_id;

	/**
	 * 资讯模块名称
	 */
	private String article_mod_name;

	/**
	 * 作者
	 */
	private String author;

	/**
	 * 来源
	 */
	private String source;

	/**
	 * 主图地址
	 */
	private String img_path;

	/**
	 * 主图说明
	 */
	private String img_desc;

	/**
	 * 摘要
	 */
	private String summary;

	/**
	 * 排序值
	 */
	private Long order_value;

	/**
	 * 是否置顶：0-否，1-是
	 */
	private Long is_top;

	/**
	 * 是否显示在首页：0-否，1-是
	 */
	private Long is_display_index;

	/**
	 * 是否启用外链：0-不启用，1-启用
	 */
	private Long is_link_out;

	/**
	 * 外链地址
	 */
	private String link_out_addr;

	/**
	 * 浏览次数
	 */
	private Long view_counts;

	/**
	 * 发布地区
	 */
	private Long pub_p_index;

	/**
	 * 发布时间
	 */
	private Date pub_date;

	/**
	 * 信息状态：0-未发布，1-已发布
	 */
	private Long states;

	/**
	 * 添加人
	 */
	private Long add_user_id;

	/**
	 * 添加人用户名
	 */
	private String add_user_name;

	/**
	 * 添加人生产企业ID(STD_ENTP_PROD.ENTP_ID)
	 */
	private Long add_prod_entp_id;

	/**
	 * 添加人生产企业名称
	 */
	private String add_prod_entp_name;

	/**
	 * 添加时间
	 */
	private Date add_date;

	/**
	 * 是否删除：0-未删除，1-已删除
	 */
	private Long is_del;

	/**
	 * 删除时间
	 */
	private Date del_date;

	/**
	 * 删除人
	 */
	private Long del_user_id;

	/**
	 * 投放网点类别
	 */
	private Long shop_category_id;

	/**
	 * MMT审核
	 */
	private Long mmt_audit;

	/**
	 * 投放位置
	 * 
	 * @return
	 */
	private Long public_place;

	/**
	 * MMT审核备注
	 */
	private String mmt_audit_desc;

	private String content;

	private String upload_image_files;

	private String areas_ids;

	private String areas_names;

	private Integer msg_info_type;

	private Integer is_sent;

	private String role_ids;

	private String role_names;

	private String dept_ids;

	private String dept_names;

	private Long group_id;

	private Long dept_id;

	private List<KonkaPeAttachments> konkaPeAttachments;

	private List<KonkaPePublicScope> konkaPePublicScopeList;

	public String getContent() {
		return content;
	}

	public void setContent(String content) {
		this.content = content;
	}

	public Long getShop_category_id() {
		return shop_category_id;
	}

	public void setShop_category_id(Long shop_category_id) {
		this.shop_category_id = shop_category_id;
	}

	public String getUpload_image_files() {
		return upload_image_files;
	}

	public void setUpload_image_files(String upload_image_files) {
		this.upload_image_files = upload_image_files;
	}

	public List<KonkaPeAttachments> getKonkaPeAttachments() {
		return konkaPeAttachments;
	}

	public void setKonkaPeAttachments(List<KonkaPeAttachments> konkaPeAttachments) {
		this.konkaPeAttachments = konkaPeAttachments;
	}

	public KonkaPeArticleInfo() {

	}

	public void setId(Long id) {
		this.id = id;
	}

	public Long getId() {
		return id;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public String getTitle() {
		return title;
	}

	public void setShort_title(String short_title) {
		this.short_title = short_title;
	}

	public String getShort_title() {
		return short_title;
	}

	public void setKey_words(String key_words) {
		this.key_words = key_words;
	}

	public String getKey_words() {
		return key_words;
	}

	public void setArticle_mod_id(Long article_mod_id) {
		this.article_mod_id = article_mod_id;
	}

	public Long getArticle_mod_id() {
		return article_mod_id;
	}

	public void setArticle_type_id(Long article_type_id) {
		this.article_type_id = article_type_id;
	}

	public Long getArticle_type_id() {
		return article_type_id;
	}

	public void setArticle_mod_name(String article_mod_name) {
		this.article_mod_name = article_mod_name;
	}

	public String getArticle_mod_name() {
		return article_mod_name;
	}

	public void setAuthor(String author) {
		this.author = author;
	}

	public String getAuthor() {
		return author;
	}

	public void setSource(String source) {
		this.source = source;
	}

	public String getSource() {
		return source;
	}

	public void setImg_path(String img_path) {
		this.img_path = img_path;
	}

	public String getImg_path() {
		return img_path;
	}

	public void setImg_desc(String img_desc) {
		this.img_desc = img_desc;
	}

	public String getImg_desc() {
		return img_desc;
	}

	public void setSummary(String summary) {
		this.summary = summary;
	}

	public String getSummary() {
		return summary;
	}

	public void setOrder_value(Long order_value) {
		this.order_value = order_value;
	}

	public Long getOrder_value() {
		return order_value;
	}

	public void setIs_top(Long is_top) {
		this.is_top = is_top;
	}

	public Long getIs_top() {
		return is_top;
	}

	public void setIs_display_index(Long is_display_index) {
		this.is_display_index = is_display_index;
	}

	public Long getIs_display_index() {
		return is_display_index;
	}

	public void setIs_link_out(Long is_link_out) {
		this.is_link_out = is_link_out;
	}

	public Long getIs_link_out() {
		return is_link_out;
	}

	public void setLink_out_addr(String link_out_addr) {
		this.link_out_addr = link_out_addr;
	}

	public String getLink_out_addr() {
		return link_out_addr;
	}

	public void setView_counts(Long view_counts) {
		this.view_counts = view_counts;
	}

	public Long getView_counts() {
		return view_counts;
	}

	public void setPub_p_index(Long pub_p_index) {
		this.pub_p_index = pub_p_index;
	}

	public Long getPub_p_index() {
		return pub_p_index;
	}

	public void setPub_date(Date pub_date) {
		this.pub_date = pub_date;
	}

	public Date getPub_date() {
		return pub_date;
	}

	public void setStates(Long states) {
		this.states = states;
	}

	public Long getStates() {
		return states;
	}

	public void setAdd_user_id(Long add_user_id) {
		this.add_user_id = add_user_id;
	}

	public Long getAdd_user_id() {
		return add_user_id;
	}

	public void setAdd_user_name(String add_user_name) {
		this.add_user_name = add_user_name;
	}

	public String getAdd_user_name() {
		return add_user_name;
	}

	public void setAdd_prod_entp_id(Long add_prod_entp_id) {
		this.add_prod_entp_id = add_prod_entp_id;
	}

	public Long getAdd_prod_entp_id() {
		return add_prod_entp_id;
	}

	public void setAdd_prod_entp_name(String add_prod_entp_name) {
		this.add_prod_entp_name = add_prod_entp_name;
	}

	public String getAdd_prod_entp_name() {
		return add_prod_entp_name;
	}

	public void setAdd_date(Date add_date) {
		this.add_date = add_date;
	}

	public Date getAdd_date() {
		return add_date;
	}

	public void setIs_del(Long is_del) {
		this.is_del = is_del;
	}

	public Long getIs_del() {
		return is_del;
	}

	public void setDel_date(Date del_date) {
		this.del_date = del_date;
	}

	public Date getDel_date() {
		return del_date;
	}

	public void setDel_user_id(Long del_user_id) {
		this.del_user_id = del_user_id;
	}

	public Long getDel_user_id() {
		return del_user_id;
	}

	public Long getMmt_audit() {
		return mmt_audit;
	}

	public void setMmt_audit(Long mmt_audit) {
		this.mmt_audit = mmt_audit;
	}

	public String getMmt_audit_desc() {
		return mmt_audit_desc;
	}

	public void setMmt_audit_desc(String mmt_audit_desc) {
		this.mmt_audit_desc = mmt_audit_desc;
	}

	public Long getPublic_place() {
		return public_place;
	}

	public void setPublic_place(Long public_place) {
		this.public_place = public_place;
	}

	public String getAreas_ids() {
		return areas_ids;
	}

	public void setAreas_ids(String areas_ids) {
		this.areas_ids = areas_ids;
	}

	public String getAreas_names() {
		return areas_names;
	}

	public void setAreas_names(String areas_names) {
		this.areas_names = areas_names;
	}

	public List<KonkaPePublicScope> getKonkaPePublicScopeList() {
		return konkaPePublicScopeList;
	}

	public void setKonkaPePublicScopeList(List<KonkaPePublicScope> konkaPePublicScopeList) {
		this.konkaPePublicScopeList = konkaPePublicScopeList;
	}

	@Override
	public String toString() {
		return ReflectionToStringBuilder.toString(this, ToStringStyle.MULTI_LINE_STYLE);
	}

	/**
	 * @var 信息类别：0-公开，1-非公开
	 */
	public void setMsg_info_type(Integer msg_info_type) {
		this.msg_info_type = msg_info_type;
	}

	/**
	 * @var 信息类别：0-公开，1-非公开
	 */
	public Integer getMsg_info_type() {
		return msg_info_type;
	}

	/**
	 * @var 是否推送：0-是，1-否
	 */
	public void setIs_sent(Integer is_sent) {
		this.is_sent = is_sent;
	}

	/**
	 * @var 是否推送：0-是，1-否
	 */
	public Integer getIs_sent() {
		return is_sent;
	}

	/**
	 * @var 选择职位ID
	 */
	public void setRole_ids(String role_ids) {
		this.role_ids = role_ids;
	}

	/**
	 * @var 选择职位ID
	 */
	public String getRole_ids() {
		return role_ids;
	}

	/**
	 * @var 选择职位
	 */
	public void setRole_names(String role_names) {
		this.role_names = role_names;
	}

	/**
	 * @var 选择职位
	 */
	public String getRole_names() {
		return role_names;
	}

	/**
	 * @var 选择分公司ID
	 */
	public void setDept_ids(String dept_ids) {
		this.dept_ids = dept_ids;
	}

	/**
	 * @var 选择分公司ID
	 */
	public String getDept_ids() {
		return dept_ids;
	}

	/**
	 * @var 选择分公司
	 */
	public void setDept_names(String dept_names) {
		this.dept_names = dept_names;
	}

	/**
	 * @var 选择分公司
	 */
	public String getDept_names() {
		return dept_names;
	}

	/**
	 * @var 群组ID
	 */
	public void setGroup_id(Long group_id) {
		this.group_id = group_id;
	}

	/**
	 * @var 群组ID
	 */
	public Long getGroup_id() {
		return group_id;
	}

	public Long getDept_id() {
		return dept_id;
	}

	public void setDept_id(Long deptId) {
		dept_id = deptId;
	}

}