package com.ebiz.mmt.domain;

import java.io.Serializable;
import java.util.Date;

import org.apache.commons.lang.builder.ReflectionToStringBuilder;
import org.apache.commons.lang.builder.ToStringStyle;

import com.ebiz.ssi.domain.BaseDomain;

/**
 * Code by AutoGenerated Builder
 * AutoGenerated Builder Version 2.1
 * @author Hui,Gang
 * @datetime 2011-11-10 15:33:15
 */
 public class KonkaR3Backmoney extends BaseDomain implements Serializable {
 	
 	private static final long serialVersionUID = -1L;

	/**
	 * ID
	 */
    private Long id;
           
    private Date add_date;
           
    private Long add_uid;
           
    private Long year;
           
	/**
	 * 分公司所在地名称
	 */
    private String branch_area_name;
           
	/**
	 * 分公司所在地编号
	 */
    private Long branch_area_code;
           
	/**
	 * 经办名称
	 */
    private String handle_name;
           
	/**
	 * R3编码
	 */
    private String r3_code;
           
	/**
	 * 客户群类型
	 */
    private String customer_type;
           
	/**
	 * 所在区域名称
	 */
    private String area_name;
           
	/**
	 * 所在区域编号
	 */
    private Long area_code;
           
	/**
	 * 客户名称
	 */
    private String customer_name;
           
	/**
	 * 1月
	 */
    private Double column_1;
           
	/**
	 * 2月
	 */
    private Double column_2;
           
	/**
	 * 3月
	 */
    private Double column_3;
           
	/**
	 * 4月
	 */
    private Double column_4;
           
	/**
	 * 5月
	 */
    private Double column_5;
           
	/**
	 * 6月
	 */
    private Double column_6;
           
	/**
	 * 7月
	 */
    private Double column_7;
           
	/**
	 * 8月
	 */
    private Double column_8;
           
	/**
	 * 9月
	 */
    private Double column_9;
           
	/**
	 * 10月
	 */
    private Double column_10;
           
	/**
	 * 11月
	 */
    private Double column_11;
           
	/**
	 * 12月
	 */
    private Double column_12;
           
	public KonkaR3Backmoney() {

	}
 
 	public void setId(Long id) {
		this.id = id;
	}
	
	public Long getId() {
		return id;
	}
           
 	public void setAdd_date(Date add_date) {
		this.add_date = add_date;
	}
	
	public Date getAdd_date() {
		return add_date;
	}
           
 	public void setAdd_uid(Long add_uid) {
		this.add_uid = add_uid;
	}
	
	public Long getAdd_uid() {
		return add_uid;
	}
           
 	public void setYear(Long year) {
		this.year = year;
	}
	
	public Long getYear() {
		return year;
	}
           
 	public void setBranch_area_name(String branch_area_name) {
		this.branch_area_name = branch_area_name;
	}
	
	public String getBranch_area_name() {
		return branch_area_name;
	}
           
 	public void setBranch_area_code(Long branch_area_code) {
		this.branch_area_code = branch_area_code;
	}
	
	public Long getBranch_area_code() {
		return branch_area_code;
	}
           
 	public void setHandle_name(String handle_name) {
		this.handle_name = handle_name;
	}
	
	public String getHandle_name() {
		return handle_name;
	}
           
 	public void setR3_code(String r3_code) {
		this.r3_code = r3_code;
	}
	
	public String getR3_code() {
		return r3_code;
	}
           
 	public void setCustomer_type(String customer_type) {
		this.customer_type = customer_type;
	}
	
	public String getCustomer_type() {
		return customer_type;
	}
           
 	public void setArea_name(String area_name) {
		this.area_name = area_name;
	}
	
	public String getArea_name() {
		return area_name;
	}
           
 	public void setArea_code(Long area_code) {
		this.area_code = area_code;
	}
	
	public Long getArea_code() {
		return area_code;
	}
           
 	public void setCustomer_name(String customer_name) {
		this.customer_name = customer_name;
	}
	
	public String getCustomer_name() {
		return customer_name;
	}
           
 	
           
	public Double getColumn_1() {
		return column_1;
	}

	public void setColumn_1(Double column_1) {
		this.column_1 = column_1;
	}

	public Double getColumn_2() {
		return column_2;
	}

	public void setColumn_2(Double column_2) {
		this.column_2 = column_2;
	}

	public Double getColumn_3() {
		return column_3;
	}

	public void setColumn_3(Double column_3) {
		this.column_3 = column_3;
	}

	public Double getColumn_4() {
		return column_4;
	}

	public void setColumn_4(Double column_4) {
		this.column_4 = column_4;
	}

	public Double getColumn_5() {
		return column_5;
	}

	public void setColumn_5(Double column_5) {
		this.column_5 = column_5;
	}

	public Double getColumn_6() {
		return column_6;
	}

	public void setColumn_6(Double column_6) {
		this.column_6 = column_6;
	}

	public Double getColumn_7() {
		return column_7;
	}

	public void setColumn_7(Double column_7) {
		this.column_7 = column_7;
	}

	public Double getColumn_8() {
		return column_8;
	}

	public void setColumn_8(Double column_8) {
		this.column_8 = column_8;
	}

	public Double getColumn_9() {
		return column_9;
	}

	public void setColumn_9(Double column_9) {
		this.column_9 = column_9;
	}

	public Double getColumn_10() {
		return column_10;
	}

	public void setColumn_10(Double column_10) {
		this.column_10 = column_10;
	}

	public Double getColumn_11() {
		return column_11;
	}

	public void setColumn_11(Double column_11) {
		this.column_11 = column_11;
	}

	public Double getColumn_12() {
		return column_12;
	}

	public void setColumn_12(Double column_12) {
		this.column_12 = column_12;
	}

	@Override 
    public String toString() { 
   		return ReflectionToStringBuilder.toString(this, ToStringStyle.MULTI_LINE_STYLE);
    }
    
 }