package com.ebiz.mmt.domain;

import java.io.Serializable;
import java.util.Date;

import org.apache.commons.lang.builder.ReflectionToStringBuilder;
import org.apache.commons.lang.builder.ToStringStyle;

import com.ebiz.ssi.domain.BaseDomain;

/**
 * Code by AutoGenerated Builder AutoGenerated Builder Version 2.1
 * 
 * @author Hui,Gang
 * @datetime 2011-09-28 18:29:20
 */
public class KonkaPeArticleType extends BaseDomain implements Serializable {

	private static final long serialVersionUID = -1L;

	/**
	 * ID
	 */
	private Long id;

	/**
	 * 类别名称
	 */
	private String type_name;

	/**
	 * 部门ID
	 */
	private Long dept_id;

	/**
	 * 添加人ID
	 */
	private Long add_user_id;

	/**
	 * 添加时间
	 */
	private Date add_datetime;

	private Integer is_del;

	public KonkaPeArticleType() {

	}

	public void setId(Long id) {
		this.id = id;
	}

	public Long getId() {
		return id;
	}

	public void setType_name(String type_name) {
		this.type_name = type_name;
	}

	public String getType_name() {
		return type_name;
	}

	public void setDept_id(Long dept_id) {
		this.dept_id = dept_id;
	}

	public Long getDept_id() {
		return dept_id;
	}

	public void setAdd_user_id(Long add_user_id) {
		this.add_user_id = add_user_id;
	}

	public Long getAdd_user_id() {
		return add_user_id;
	}

	public void setAdd_datetime(Date add_datetime) {
		this.add_datetime = add_datetime;
	}

	public Date getAdd_datetime() {
		return add_datetime;
	}

	@Override
	public String toString() {
		return ReflectionToStringBuilder.toString(this, ToStringStyle.MULTI_LINE_STYLE);
	}

	/**
	 * @var 是否删除：0-否，1-是
	 */
	public void setIs_del(Integer is_del) {
		this.is_del = is_del;
	}

	/**
	 * @var 是否删除：0-否，1-是
	 */
	public Integer getIs_del() {
		return is_del;
	}

}