package com.ebiz.mmt.domain;

import java.io.Serializable;
import java.util.Date;

import org.apache.commons.lang.builder.ReflectionToStringBuilder;
import org.apache.commons.lang.builder.ToStringStyle;

import com.ebiz.ssi.domain.BaseDomain;

/**
 * Code by AutoGenerated Builder
 * AutoGenerated Builder Version 2.1
 * @author Hui,Gang
 * @datetime 2011-11-14 10:15:03
 */
 public class TaskPara extends BaseDomain implements Serializable {
 	
 	private static final long serialVersionUID = -1L;

	/**
	 * ID
	 */
    private Long id;
           
	/**
	 * 增加时间
	 */
    private Date add_date;
           
	/**
	 * 增加用户ID
	 */
    private Long add_uid;
           
	/**
	 * 年度
	 */
    private Integer year;
           
	/**
	 * 名称
	 */
    private String task_name;
           
    private Double column_1;
           
    private Double column_2;
           
    private Double column_3;
           
    private Double column_4;
           
    private Double column_5;
           
    private Double column_6;
           
    private Double column_7;
           
    private Double column_8;
           
    private Double column_9;
           
    private Double column_10;
           
    private Double column_11;
           
    private Double column_12;
           
    private Double year_task;
           
    private Double year_para;
           
	/**
	 * 排序值
	 */
    private Long order_value;
           
	public TaskPara() {

	}
 
 	public void setId(Long id) {
		this.id = id;
	}
	
	public Long getId() {
		return id;
	}
           
 	public void setAdd_date(Date add_date) {
		this.add_date = add_date;
	}
	
	public Date getAdd_date() {
		return add_date;
	}
           
 	public void setAdd_uid(Long add_uid) {
		this.add_uid = add_uid;
	}
	
	public Long getAdd_uid() {
		return add_uid;
	}
           
 	public void setYear(Integer year) {
		this.year = year;
	}
	
	public Integer getYear() {
		return year;
	}
           
 	public void setTask_name(String task_name) {
		this.task_name = task_name;
	}
	
	public String getTask_name() {
		return task_name;
	}
           
 	public void setColumn_1(Double column_1) {
		this.column_1 = column_1;
	}
	
	public Double getColumn_1() {
		return column_1;
	}
           
 	public void setColumn_2(Double column_2) {
		this.column_2 = column_2;
	}
	
	public Double getColumn_2() {
		return column_2;
	}
           
 	public void setColumn_3(Double column_3) {
		this.column_3 = column_3;
	}
	
	public Double getColumn_3() {
		return column_3;
	}
           
 	public void setColumn_4(Double column_4) {
		this.column_4 = column_4;
	}
	
	public Double getColumn_4() {
		return column_4;
	}
           
 	public void setColumn_5(Double column_5) {
		this.column_5 = column_5;
	}
	
	public Double getColumn_5() {
		return column_5;
	}
           
 	public void setColumn_6(Double column_6) {
		this.column_6 = column_6;
	}
	
	public Double getColumn_6() {
		return column_6;
	}
           
 	public void setColumn_7(Double column_7) {
		this.column_7 = column_7;
	}
	
	public Double getColumn_7() {
		return column_7;
	}
           
 	public void setColumn_8(Double column_8) {
		this.column_8 = column_8;
	}
	
	public Double getColumn_8() {
		return column_8;
	}
           
 	public void setColumn_9(Double column_9) {
		this.column_9 = column_9;
	}
	
	public Double getColumn_9() {
		return column_9;
	}
           
 	public void setColumn_10(Double column_10) {
		this.column_10 = column_10;
	}
	
	public Double getColumn_10() {
		return column_10;
	}
           
 	public void setColumn_11(Double column_11) {
		this.column_11 = column_11;
	}
	
	public Double getColumn_11() {
		return column_11;
	}
           
 	public void setColumn_12(Double column_12) {
		this.column_12 = column_12;
	}
	
	public Double getColumn_12() {
		return column_12;
	}
           
 	public void setYear_task(Double year_task) {
		this.year_task = year_task;
	}
	
	public Double getYear_task() {
		return year_task;
	}
           
 	public void setYear_para(Double year_para) {
		this.year_para = year_para;
	}
	
	public Double getYear_para() {
		return year_para;
	}
           
 	public void setOrder_value(Long order_value) {
		this.order_value = order_value;
	}
	
	public Long getOrder_value() {
		return order_value;
	}
           
	@Override 
    public String toString() { 
   		return ReflectionToStringBuilder.toString(this, ToStringStyle.MULTI_LINE_STYLE);
    }
    
 }