package com.ebiz.mmt.dao;

import java.util.List;

import org.springframework.dao.DataAccessException;

import com.ebiz.mmt.domain.KonkaPeArticleInfo;
import com.ebiz.ssi.dao.EntityDao;

/**
 * Code by AutoGenerated Builder AutoGenerated Builder Version 2.1
 * 
 * @author Hui,Gang
 * @datetime 2011-09-29 17:05:13
 */
public interface KonkaPeArticleInfoDao extends EntityDao<KonkaPeArticleInfo> {

	Long selectKonkaPeArticleInfoCountForReceive(KonkaPeArticleInfo t) throws DataAccessException;

	List<KonkaPeArticleInfo> selectKonkaPeArticleInfoPaginatedListForReceive(KonkaPeArticleInfo t)
			throws DataAccessException;

	/**
	 * @author Hu,Hao
	 * @version 2013-05-30
	 */
	List<KonkaPeArticleInfo> selectKonkaPeArticleInfoForMobilePaginatedList(KonkaPeArticleInfo t)
			throws DataAccessException;

	/**
	 * @author Hu,Hao
	 * @version 2013-05-30
	 */
	Long selectKonkaPeArticleInfoForMobileCount(KonkaPeArticleInfo t);
	
	/**
	 * @author Hu,Hao
	 * @version 2013-07-14
	 */
	List<KonkaPeArticleInfo> selectKonkaPeArticleInfoForGroupPaginatedList(KonkaPeArticleInfo t);
	
}