package com.ebiz.mmt.dao;

import com.ebiz.mmt.domain.KonkaR3MmtMatch;
import com.ebiz.ssi.dao.EntityDao;

/**
 * Code by AutoGenerated Builder AutoGenerated Builder Version 2.1
 * 
 * @author Hui,Gang
 * @datetime 2011-09-24 14:50:49
 */
public interface KonkaR3MmtMatchDao extends EntityDao<KonkaR3MmtMatch> {
	public KonkaR3MmtMatch selectKonkaR3MmtMatchBySelf(KonkaR3MmtMatch t);

	public KonkaR3MmtMatch selectKonkaR3MmtMatchByR3ShopId(KonkaR3MmtMatch t);
}