package com.ebiz.mmt.dao;

import com.ebiz.mmt.domain.KonkaPeArticleUserMsg;
import com.ebiz.ssi.dao.EntityDao;

/**
 * Code by AutoGenerated Builder
 * AutoGenerated Builder Version 2.1
 * @author Hui,Gang
 * @datetime 2011-09-29 17:05:13
 */
public interface KonkaPeArticleUserMsgDao extends EntityDao<KonkaPeArticleUserMsg> {

}