package com.ebiz.mmt.dao.ibatis;

import java.util.List;

import org.springframework.stereotype.Repository;

import com.ebiz.ssi.dao.ibatis.EntityDaoSqlMapImpl;
import com.ebiz.mmt.dao.KonkaR3BackmoneyDao;
import com.ebiz.mmt.domain.KonkaR3Backmoney;

/**
 * Code by AutoGenerated Builder AutoGenerated Builder Version 2.1
 * 
 * @author Hui,Gang
 * @datetime 2011-11-10 15:33:16
 */
@Repository
public class KonkaR3BackmoneyDaoSqlMapImpl extends EntityDaoSqlMapImpl<KonkaR3Backmoney> implements KonkaR3BackmoneyDao {

	/**
	 * @author Hu,hao
	 * @version 2013-07-05
	 */
	@SuppressWarnings("unchecked")
	public List<KonkaR3Backmoney> selectKonkaR3BackmoneyListForTb(KonkaR3Backmoney t) {
		return super.getSqlMapClientTemplate().queryForList("selectKonkaR3BackmoneyListForTb", t);
	}

	/**
	 * @author Hu,hao
	 * @version 2013-09-13
	 */
	@SuppressWarnings("unchecked")
	public List<KonkaR3Backmoney> selectKonkaR3BackmoneyForMonth(KonkaR3Backmoney t) {
		return super.getSqlMapClientTemplate().queryForList("selectKonkaR3BackmoneyForMonth", t);
	}

	/**
	 * @author Hu,hao
	 * @version 2013-09-17
	 */
	@SuppressWarnings("unchecked")
	@Override
	public List<KonkaR3Backmoney> selectKonkaR3BackmoneyListForHkJd(KonkaR3Backmoney t) {
		return super.getSqlMapClientTemplate().queryForList("selectKonkaR3BackmoneyListForHkJd", t);
	}

	/**
	 * @author Hu,hao
	 * @version 2013-10-11
	 * @desc 根据用户的数据权限查询R3回款信息
	 */
	@Override
	public Long selectKonkaR3BackmoneyForRoleDataCount(KonkaR3Backmoney t) {
		return (Long) super.getSqlMapClientTemplate().queryForObject("selectKonkaR3BackmoneyForRoleDataCount", t);
	}

	/**
	 * @author Hu,hao
	 * @version 2013-10-11
	 * @desc 根据用户的数据权限查询R3回款信息
	 */
	@SuppressWarnings("unchecked")
	@Override
	public List<KonkaR3Backmoney> selectKonkaR3BackmoneyForRoleDataPaginatedList(KonkaR3Backmoney t) {
		return super.getSqlMapClientTemplate().queryForList("selectKonkaR3BackmoneyForRoleDataPaginatedList", t);
	}

	/**
	 * @author Hu,hao
	 * @version 2013-11-06
	 * @desc 回款数据
	 */
	@SuppressWarnings("unchecked")
	public List<KonkaR3Backmoney> selectKonkaR3BackmoneyFoHkDataPaginatedList(KonkaR3Backmoney t) {
		return super.getSqlMapClientTemplate().queryForList("selectKonkaR3BackmoneyFoHkDataPaginatedList", t);
	}

	/**
	 * @author Hu,hao
	 * @version 2013-11-06
	 * @desc 零售数据
	 */
	@SuppressWarnings("unchecked")
	public List<KonkaR3Backmoney> selectKonkaR3BackmoneyFoSailDataPaginatedList(KonkaR3Backmoney t) {
		return super.getSqlMapClientTemplate().queryForList("selectKonkaR3BackmoneyFoSailDataPaginatedList", t);
	}

	/**
	 * @author Hu,hao
	 * @version 2013-11-06
	 * @desc 结算数据
	 */
	@SuppressWarnings("unchecked")
	public List<KonkaR3Backmoney> selectKonkaR3BackmoneyFoJsDataPaginatedList(KonkaR3Backmoney t) {
		return super.getSqlMapClientTemplate().queryForList("selectKonkaR3BackmoneyFoJsDataPaginatedList", t);
	}

	/**
	 * @author Hu,hao
	 * @version 2013-11-06
	 * @desc 结算数据
	 */
	@SuppressWarnings("unchecked")
	public List<KonkaR3Backmoney> selectKonkaR3BackmoneyFoRwDataPaginatedList(KonkaR3Backmoney t) {
		return super.getSqlMapClientTemplate().queryForList("selectKonkaR3BackmoneyFoRwDataPaginatedList", t);
	}

	/**
	 * @author Hu,hao
	 * @version 2013-12-05
	 * @desc 首页展示数据
	 */
	@SuppressWarnings("unchecked")
	public List<KonkaR3Backmoney> selectKonkaR3SailAndJsDataToIndexPaginatedList(KonkaR3Backmoney t) {
		return super.getSqlMapClientTemplate().queryForList("selectKonkaR3SailAndJsDataToIndexPaginatedList", t);
	}

}