package com.ebiz.mmt.domain;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;
import java.util.List;

import org.apache.commons.lang.builder.ReflectionToStringBuilder;
import org.apache.commons.lang.builder.ToStringStyle;

import com.ebiz.ssi.domain.BaseDomain;

/**
 * Code by AutoGenerated Builder AutoGenerated Builder Version 2.1
 * 
 * @author Hui,Gang
 * @datetime 2011-09-24 14:50:49
 */
public class KonkaR3Shop extends BaseDomain implements Serializable {

	private static final long serialVersionUID = -1L;

	/**
	 * ID
	 */
	private Long id;

	/**
	 * 所在区域编号
	 */
	private Long area_code;

	/**
	 * 所在区域名称
	 */
	private String area_name;

	/**
	 * 分公司所在地编号
	 */
	private Long branch_area_code;

	/**
	 * 分公司所在地名称
	 */
	private String branch_area_name;

	/**
	 * 客户群类型
	 */
	private String customer_type;

	/**
	 * 交易状态
	 */
	private Integer status;

	/**
	 * R3编码
	 */
	private String r3_code;

	/**
	 * 经办名称
	 */
	private String handle_name;

	/**
	 * 分公司所在地编号_2
	 */
	private Long branch_area_code_2;

	/**
	 * 分公司所在地名称_2
	 */
	private String branch_area_name_2;

	/**
	 * 合并客户编码
	 */
	private String customer_code;

	/**
	 * 客户名称
	 */
	private String customer_name;

	/**
	 * 备注
	 */
	private String r3_desc;

	/**
	 * 2010合并编码
	 */
	private String merge_code_2010;

	/**
	 * 导入日期
	 */
	private Date import_date;

	/**
	 * 导入人编号
	 */
	private Long import_user_id;

	/**
	 * 是否删除 0否1是
	 */
	private Long is_del;
	
	/**
	 * R3的删除标志
	 * 
	 */
	private Long is_loevm;
	
	/**
	 * R3的销售冻结
	 */
	private Long is_cassd;

	/**
	 * 是否完成匹配 0否1是
	 */
	private Long is_match;

	private Long shop_id;

	private String shop_name;

	private List<TaskPara> taskParaList;

	private PeProdUser peProdUser;

	private String b_lng;

	private String b_lat;

	private String link_man_name;

	private String link_man_tel;

	private String link_man_mobile;

	private String link_man_addr;

	private String link_man_post;

	private String host_name;

	private String host_tel;

	private String r3_sales_org_code;

	/**
	 * @val 触网类型：1、触网1 2、触网2
	 */
	private Integer web_type;
	/**
	 * 创建时间
	 */
	private Date add_date;

	private Date create_date;

	private BigDecimal last_year_money;

	private BigDecimal last_year_back_money;

	private BigDecimal entp_reg_money;

	private String entp_scale;

	private String entp_man_count;

	private String entp_tel;

	private Date entp_birthday;

	private String entp_fax;

	private String entp_post;

	private String entp_p_level;

	private String entp_addr;

	private String entp_www;

	private String entp_main_pds;

	private String entp_sale_area;

	private String entp_inro;

	private Long entp_type;

	private Long entp_p_index;

	private Integer is_konka;// 康佳合作客户标识:0-非康佳客户;1-康佳客户

	// 目前系统对于客户只能分两类标识客户了,一类是售达方,一类是送达方
	// is_sdf = 0 代表售达方,is_sdf =1就是除了售达方以外的分类了.
	private Integer is_sdf;// 是否是送达方：0表示否，1表示是

	private Integer is_minus_sales;

	private Integer is_inventory;// 是否允许盘存
	
	private String add_name;//维护人姓名
	
	private Long modify_user_id;//维护人ID
	
	private Date stop_date;  //停用时间

	String[] r3_link_position;

	String[] r3_link_real_name;

	String[] r3_link_sex;

	String[] r3_link_birthday;

	String[] r3_link_tel;

	String[] r3_link_email;

	String[] r3_link_favor; 
	
	String[] r3_link_job;   //岗位
	
	String[] r3_link_telephone;  //固定电话
	
	String[] r3_link_fax;   //传真
	
	String[] r3_link_weixin;  //微信号
	
	String[] r3_link_qq;    //QQ
	
	String[] r3_link_default;  //是否默认
	
	String[] r3_link_valid;   //是否有效
	
	String[] brand_id;   //品牌ID
	
	String[] sale_year;   //销售年份
	
	String[] annual_salse;   //年销售额
	
	String[] sale_rank;   //销售排名

	private List<Attachment> attachmentList;// 附件
	
	
	//****add by Lianghouen on 2014-06-12****/
	private String shop_status;  //客户状态
	private String branch_name;  //事业部
	//***************************************/

	public String getShop_status() {
		return shop_status;
	}

	public void setShop_status(String shopStatus) {
		this.shop_status = shopStatus;
	}

	public KonkaR3Shop() {

	}

	public List<TaskPara> getTaskParaList() {
		return taskParaList;
	}

	public void setTaskParaList(List<TaskPara> taskParaList) {
		this.taskParaList = taskParaList;
	}

	public Long getShop_id() {
		return shop_id;
	}

	public void setShop_id(Long shop_id) {
		this.shop_id = shop_id;
	}

	public String getShop_name() {
		return shop_name;
	}

	public void setShop_name(String shop_name) {
		this.shop_name = shop_name;
	}

	public Long getIs_match() {
		return is_match;
	}

	public void setIs_match(Long isMatch) {
		is_match = isMatch;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public Long getId() {
		return id;
	}

	public void setArea_code(Long area_code) {
		this.area_code = area_code;
	}

	public Long getArea_code() {
		return area_code;
	}

	public void setArea_name(String area_name) {
		this.area_name = area_name;
	}

	public String getArea_name() {
		return area_name;
	}

	public void setBranch_area_code(Long branch_area_code) {
		this.branch_area_code = branch_area_code;
	}

	public Long getBranch_area_code() {
		return branch_area_code;
	}

	public void setBranch_area_name(String branch_area_name) {
		this.branch_area_name = branch_area_name;
	}

	public String getBranch_area_name() {
		return branch_area_name;
	}

	public void setCustomer_type(String customer_type) {
		this.customer_type = customer_type;
	}

	public String getCustomer_type() {
		return customer_type;
	}

	public void setStatus(Integer status) {
		this.status = status;
	}

	public Integer getStatus() {
		return status;
	}

	public void setR3_code(String r3_code) {
		this.r3_code = r3_code;
	}

	public String getR3_code() {
		return r3_code;
	}

	public void setHandle_name(String handle_name) {
		this.handle_name = handle_name;
	}

	public String getHandle_name() {
		return handle_name;
	}

	public void setBranch_area_code_2(Long branch_area_code_2) {
		this.branch_area_code_2 = branch_area_code_2;
	}

	public Long getBranch_area_code_2() {
		return branch_area_code_2;
	}

	public void setBranch_area_name_2(String branch_area_name_2) {
		this.branch_area_name_2 = branch_area_name_2;
	}

	public String getBranch_area_name_2() {
		return branch_area_name_2;
	}

	public void setCustomer_code(String customer_code) {
		this.customer_code = customer_code;
	}

	public String getCustomer_code() {
		return customer_code;
	}

	public void setCustomer_name(String customer_name) {
		this.customer_name = customer_name;
	}

	public String getCustomer_name() {
		return customer_name;
	}

	public void setR3_desc(String r3_desc) {
		this.r3_desc = r3_desc;
	}

	public String getR3_desc() {
		return r3_desc;
	}

	public void setMerge_code_2010(String merge_code_2010) {
		this.merge_code_2010 = merge_code_2010;
	}

	public String getMerge_code_2010() {
		return merge_code_2010;
	}

	public void setImport_date(Date import_date) {
		this.import_date = import_date;
	}

	public Date getImport_date() {
		return import_date;
	}

	public void setImport_user_id(Long import_user_id) {
		this.import_user_id = import_user_id;
	}

	public Long getImport_user_id() {
		return import_user_id;
	}

	public void setIs_del(Long is_del) {
		this.is_del = is_del;
	}

	public Long getIs_del() {
		return is_del;
	}

	@Override
	public String toString() {
		return ReflectionToStringBuilder.toString(this, ToStringStyle.MULTI_LINE_STYLE);
	}

	public PeProdUser getPeProdUser() {
		return peProdUser;
	}

	public void setPeProdUser(PeProdUser peProdUser) {
		this.peProdUser = peProdUser;
	}

	public String getB_lng() {
		return b_lng;
	}

	public void setB_lng(String bLng) {
		b_lng = bLng;
	}

	public String getB_lat() {
		return b_lat;
	}

	public void setB_lat(String bLat) {
		b_lat = bLat;
	}

	/**
	 * @val 联系人姓名
	 */
	public String getLink_man_name() {
		return link_man_name;
	}

	/**
	 * @val 联系人姓名
	 */
	public void setLink_man_name(String linkManName) {
		link_man_name = linkManName;
	}

	/**
	 * @val 联系人电话
	 */
	public String getLink_man_tel() {
		return link_man_tel;
	}

	/**
	 * @val 联系人电话
	 */
	public void setLink_man_tel(String linkManTel) {
		link_man_tel = linkManTel;
	}

	/**
	 * @val 联系人手机
	 */
	public String getLink_man_mobile() {
		return link_man_mobile;
	}

	/**
	 * @val 联系人手机
	 */
	public void setLink_man_mobile(String linkManMobile) {
		link_man_mobile = linkManMobile;
	}

	/**
	 * @val 联系人地址
	 */
	public String getLink_man_addr() {
		return link_man_addr;
	}

	/**
	 * @val 联系人地址
	 */
	public void setLink_man_addr(String linkManAddr) {
		link_man_addr = linkManAddr;
	}

	/**
	 * @val 客户邮编
	 */
	public String getLink_man_post() {
		return link_man_post;
	}

	/**
	 * @val 客户邮编
	 */
	public void setLink_man_post(String linkManPost) {
		link_man_post = linkManPost;
	}

	/**
	 * @val 法人姓名
	 */
	public String getHost_name() {
		return host_name;
	}

	/**
	 * @val 法人姓名
	 */
	public void setHost_name(String hostName) {
		host_name = hostName;
	}

	/**
	 * @val 法人联系电话
	 */
	public String getHost_tel() {
		return host_tel;
	}

	/**
	 * @val 法人联系电话
	 */
	public void setHost_tel(String hostTel) {
		host_tel = hostTel;
	}

	/**
	 * @val 创建时间
	 */
	public void setAdd_date(Date add_date) {
		this.add_date = add_date;
	}

	/**
	 * @val 创建时间
	 */
	public Date getAdd_date() {
		return add_date;
	}

	/**
	 * @val 销售组织
	 */
	public void setR3_sales_org_code(String r3_sales_org_code) {
		this.r3_sales_org_code = r3_sales_org_code;
	}

	/**
	 * @val 销售组织
	 */
	public String getR3_sales_org_code() {
		return r3_sales_org_code;
	}

	public Date getCreate_date() {
		return create_date;
	}

	public void setCreate_date(Date create_date) {
		this.create_date = create_date;
	}

	public BigDecimal getLast_year_money() {
		return last_year_money;
	}

	public void setLast_year_money(BigDecimal last_year_money) {
		this.last_year_money = last_year_money;
	}

	public BigDecimal getLast_year_back_money() {
		return last_year_back_money;
	}

	public void setLast_year_back_money(BigDecimal last_year_back_money) {
		this.last_year_back_money = last_year_back_money;
	}

	public BigDecimal getEntp_reg_money() {
		return entp_reg_money;
	}

	public void setEntp_reg_money(BigDecimal entp_reg_money) {
		this.entp_reg_money = entp_reg_money;
	}

	public String getEntp_scale() {
		return entp_scale;
	}

	public void setEntp_scale(String entp_scale) {
		this.entp_scale = entp_scale;
	}

	public String getEntp_man_count() {
		return entp_man_count;
	}

	public void setEntp_man_count(String entp_man_count) {
		this.entp_man_count = entp_man_count;
	}

	public String getEntp_tel() {
		return entp_tel;
	}

	public void setEntp_tel(String entp_tel) {
		this.entp_tel = entp_tel;
	}

	public Date getEntp_birthday() {
		return entp_birthday;
	}

	public void setEntp_birthday(Date entp_birthday) {
		this.entp_birthday = entp_birthday;
	}

	public String getEntp_fax() {
		return entp_fax;
	}

	public void setEntp_fax(String entp_fax) {
		this.entp_fax = entp_fax;
	}

	public String getEntp_post() {
		return entp_post;
	}

	public void setEntp_post(String entp_post) {
		this.entp_post = entp_post;
	}

	public String getEntp_p_level() {
		return entp_p_level;
	}

	public void setEntp_p_level(String entp_p_level) {
		this.entp_p_level = entp_p_level;
	}

	public String getEntp_addr() {
		return entp_addr;
	}

	public void setEntp_addr(String entp_addr) {
		this.entp_addr = entp_addr;
	}

	public String getEntp_www() {
		return entp_www;
	}

	public void setEntp_www(String entp_www) {
		this.entp_www = entp_www;
	}

	public String getEntp_main_pds() {
		return entp_main_pds;
	}

	public void setEntp_main_pds(String entp_main_pds) {
		this.entp_main_pds = entp_main_pds;
	}

	public String getEntp_sale_area() {
		return entp_sale_area;
	}

	public void setEntp_sale_area(String entp_sale_area) {
		this.entp_sale_area = entp_sale_area;
	}

	public String getEntp_inro() {
		return entp_inro;
	}

	public void setEntp_inro(String entp_inro) {
		this.entp_inro = entp_inro;
	}

	public Long getEntp_type() {
		return entp_type;
	}

	public void setEntp_type(Long entp_type) {
		this.entp_type = entp_type;
	}

	public Long getEntp_p_index() {
		return entp_p_index;
	}

	public void setEntp_p_index(Long entp_p_index) {
		this.entp_p_index = entp_p_index;
	}

	public String[] getR3_link_position() {
		return r3_link_position;
	}

	public void setR3_link_position(String[] r3_link_position) {
		this.r3_link_position = r3_link_position;
	}

	public String[] getR3_link_real_name() {
		return r3_link_real_name;
	}

	public void setR3_link_real_name(String[] r3_link_real_name) {
		this.r3_link_real_name = r3_link_real_name;
	}

	public String[] getR3_link_sex() {
		return r3_link_sex;
	}

	public void setR3_link_sex(String[] r3_link_sex) {
		this.r3_link_sex = r3_link_sex;
	}

	public String[] getR3_link_birthday() {
		return r3_link_birthday;
	}

	public void setR3_link_birthday(String[] r3_link_birthday) {
		this.r3_link_birthday = r3_link_birthday;
	}

	public String[] getR3_link_tel() {
		return r3_link_tel;
	}

	public void setR3_link_tel(String[] r3_link_tel) {
		this.r3_link_tel = r3_link_tel;
	}

	public String[] getR3_link_email() {
		return r3_link_email;
	}

	public void setR3_link_email(String[] r3_link_email) {
		this.r3_link_email = r3_link_email;
	}

	public String[] getR3_link_favor() {
		return r3_link_favor;
	}

	public void setR3_link_favor(String[] r3_link_favor) {
		this.r3_link_favor = r3_link_favor;
	}

	/**
	 * @是否为konka合作用户 0不是konka合作用户 1 是konka合作用户
	 */
	public Integer getIs_konka() {
		return is_konka;
	}

	/**
	 * @是否为konka合作用户 0不是konka合作用户 1 是konka合作用户
	 */
	public void setIs_konka(Integer isKonka) {
		is_konka = isKonka;
	}

	public List<Attachment> getAttachmentList() {
		return attachmentList;
	}

	public void setAttachmentList(List<Attachment> attachmentList) {
		this.attachmentList = attachmentList;
	}

	/**
	 * @val 是否是送达方：0表示否，1表示是
	 */
	public void setIs_sdf(Integer is_sdf) {
		this.is_sdf = is_sdf;
	}

	/**
	 * @val 是否是送达方：0表示否，1表示是
	 */
	public Integer getIs_sdf() {
		return is_sdf;
	}

	/**
	 * @val 是否允许负销售：0：表示允许，1表示不允许
	 */
	public void setIs_minus_sales(Integer is_minus_sales) {
		this.is_minus_sales = is_minus_sales;
	}

	/**
	 * @val 是否允许负销售：0：表示允许，1表示不允许
	 */
	public Integer getIs_minus_sales() {
		return is_minus_sales;
	}

	/**
	 * @val 触网类型：1：触网1 2：触网2
	 */
	public Integer getWeb_type() {
		return web_type;
	}

	/**
	 * @val 触网类型：1：触网1 2：触网2
	 */
	public void setWeb_type(Integer web_type) {
		this.web_type = web_type;
	}

	/**
	 * @val 是否允许盘存：0：表示允许，1表示不允许
	 */
	public Integer getIs_inventory() {
		return is_inventory;
	}

	/**
	 * @val 是否允许盘存：0：表示允许，1表示不允许
	 */
	public void setIs_inventory(Integer isInventory) {
		is_inventory = isInventory;
	}

	public void setBranch_name(String branch_name) {
		this.branch_name = branch_name;
	}

	public String getBranch_name() {
		return branch_name;
	}

	public Long getIs_loevm() {
		return is_loevm;
	}

	public void setIs_loevm(Long is_loevm) {
		this.is_loevm = is_loevm;
	}

	public Long getIs_cassd() {
		return is_cassd;
	}

	public void setIs_cassd(Long is_cassd) {
		this.is_cassd = is_cassd;
	}

	public String[] getR3_link_job() {
		return r3_link_job;
	}

	public void setR3_link_job(String[] r3_link_job) {
		this.r3_link_job = r3_link_job;
	}

	public String[] getR3_link_telephone() {
		return r3_link_telephone;
	}

	public void setR3_link_telephone(String[] r3_link_telephone) {
		this.r3_link_telephone = r3_link_telephone;
	}

	public String[] getR3_link_fax() {
		return r3_link_fax;
	}

	public void setR3_link_fax(String[] r3_link_fax) {
		this.r3_link_fax = r3_link_fax;
	}

	public String[] getR3_link_weixin() {
		return r3_link_weixin;
	}

	public void setR3_link_weixin(String[] r3_link_weixin) {
		this.r3_link_weixin = r3_link_weixin;
	}

	public String[] getR3_link_qq() {
		return r3_link_qq;
	}

	public void setR3_link_qq(String[] r3_link_qq) {
		this.r3_link_qq = r3_link_qq;
	}

	public String[] getR3_link_default() {
		return r3_link_default;
	}

	public void setR3_link_default(String[] r3_link_default) {
		this.r3_link_default = r3_link_default;
	}

	public String[] getR3_link_valid() {
		return r3_link_valid;
	}

	public void setR3_link_valid(String[] r3_link_valid) {
		this.r3_link_valid = r3_link_valid;
	}

	public String[] getBrand_id() {
		return brand_id;
	}

	public void setBrand_id(String[] brand_id) {
		this.brand_id = brand_id;
	}

	public String[] getSale_year() {
		return sale_year;
	}

	public void setSale_year(String[] sale_year) {
		this.sale_year = sale_year;
	}

	public String[] getAnnual_salse() {
		return annual_salse;
	}

	public void setAnnual_salse(String[] annual_salse) {
		this.annual_salse = annual_salse;
	}

	public String[] getSale_rank() {
		return sale_rank;
	}

	public void setSale_rank(String[] sale_rank) {
		this.sale_rank = sale_rank;
	}

	public Date getStop_date() {
		return stop_date;
	}

	public void setStop_date(Date stop_date) {
		this.stop_date = stop_date;
	}

	public String getAdd_name() {
		return add_name;
	}

	public void setAdd_name(String addName) {
		add_name = addName;
	}

	public Long getModify_user_id() {
		return modify_user_id;
	}

	public void setModify_user_id(Long modify_user_id) {
		this.modify_user_id = modify_user_id;
	}
}
