package com.ebiz.mmt.dao.ibatis;

import org.springframework.stereotype.Repository;

import com.ebiz.ssi.dao.ibatis.EntityDaoSqlMapImpl;
import com.ebiz.mmt.dao.ImportDataTypesDao;
import com.ebiz.mmt.domain.ImportDataTypes;

/**
 * Code by AutoGenerated Builder
 * AutoGenerated Builder Version 2.1
 * @author Hui,Gang
 * @datetime 2011-11-14 10:15:03
 */
@Repository
public class ImportDataTypesDaoSqlMapImpl extends EntityDaoSqlMapImpl<ImportDataTypes> implements ImportDataTypesDao {

}