package com.ebiz.mmt.dao;

import com.ebiz.mmt.domain.KonkaDeptPdLink;
import com.ebiz.ssi.dao.EntityDao;

/**
 * Code by AutoGenerated Builder
 * AutoGenerated Builder Version 2.1
 * @author Hui,Gang
 * @datetime 2011-10-10 17:03:48
 */
public interface KonkaDeptPdLinkDao extends EntityDao<KonkaDeptPdLink> {

}