package com.ebiz.mmt.domain;

import java.io.Serializable;
import java.util.Date;
import java.util.List;

import org.apache.commons.lang.builder.ReflectionToStringBuilder;
import org.apache.commons.lang.builder.ToStringStyle;

import com.ebiz.ssi.domain.BaseDomain;

/**
 * Code by AutoGenerated Builder AutoGenerated Builder Version 2.1
 * 
 * @author Hui,Gang
 * @datetime 2011-09-26 09:57:04
 */
public class PeShopCategory extends BaseDomain implements Serializable {

	private static final long serialVersionUID = -1L;

	/**
	 * 网点类别ID
	 */
	private Long category_id;

	/**
	 * 网点父类别ID
	 */
	private Long category_pid;

	/**
	 * 网点类别名称
	 */
	private String category_name;

	/**
	 * 网点类别描述
	 */
	private String category_desc;

	/**
	 * 部门ID<br />
	 * 事业部ID
	 */
	private Long dept_id;

	/**
	 * 生产企业ID:ENTP_PROD.ENTP_ID 保留字段
	 */
	private Long entp_id;

	/**
	 * 企业添加人：PE_PROD_USER.ID 保留字段
	 */
	private Long add_e_user_id;

	/**
	 * 添加人ID
	 */
	private Long add_user_id;

	/**
	 * 添加时间
	 */
	private Date add_date;

	private Integer is_lock;

	/**
	 * 是否删除
	 */
	private Long is_del;

	private List<PeShopCategory> peShopCategoryList;

	public PeShopCategory() {

	}

	public List<PeShopCategory> getPeShopCategoryList() {
		return peShopCategoryList;
	}

	public void setPeShopCategoryList(List<PeShopCategory> peShopCategoryList) {
		this.peShopCategoryList = peShopCategoryList;
	}

	public void setCategory_id(Long category_id) {
		this.category_id = category_id;
	}

	public Long getCategory_id() {
		return category_id;
	}

	public void setCategory_pid(Long category_pid) {
		this.category_pid = category_pid;
	}

	public Long getCategory_pid() {
		return category_pid;
	}

	public void setCategory_name(String category_name) {
		this.category_name = category_name;
	}

	public String getCategory_name() {
		return category_name;
	}

	public void setCategory_desc(String category_desc) {
		this.category_desc = category_desc;
	}

	public String getCategory_desc() {
		return category_desc;
	}

	public void setDept_id(Long dept_id) {
		this.dept_id = dept_id;
	}

	public Long getDept_id() {
		return dept_id;
	}

	public void setEntp_id(Long entp_id) {
		this.entp_id = entp_id;
	}

	public Long getEntp_id() {
		return entp_id;
	}

	public void setAdd_e_user_id(Long add_e_user_id) {
		this.add_e_user_id = add_e_user_id;
	}

	public Long getAdd_e_user_id() {
		return add_e_user_id;
	}

	public void setAdd_user_id(Long add_user_id) {
		this.add_user_id = add_user_id;
	}

	public Long getAdd_user_id() {
		return add_user_id;
	}

	public void setAdd_date(Date add_date) {
		this.add_date = add_date;
	}

	public Date getAdd_date() {
		return add_date;
	}

	public Integer getIs_lock() {
		return is_lock;
	}

	public void setIs_lock(Integer is_lock) {
		this.is_lock = is_lock;
	}

	public void setIs_del(Long is_del) {
		this.is_del = is_del;
	}

	public Long getIs_del() {
		return is_del;
	}

	@Override
	public String toString() {
		return ReflectionToStringBuilder.toString(this, ToStringStyle.MULTI_LINE_STYLE);
	}

}