package com.ebiz.mmt.dao.ibatis;

import org.springframework.stereotype.Repository;

import com.ebiz.ssi.dao.ibatis.EntityDaoSqlMapImpl;
import com.ebiz.mmt.dao.KonkaR3MmtMatchDao;
import com.ebiz.mmt.domain.KonkaR3MmtMatch;

/**
 * Code by AutoGenerated Builder
 * AutoGenerated Builder Version 2.1
 * @author Hui,Gang
 * @datetime 2011-09-24 14:50:49
 */
@Repository
public class KonkaR3MmtMatchDaoSqlMapImpl extends EntityDaoSqlMapImpl<KonkaR3MmtMatch> implements KonkaR3MmtMatchDao {

	@Override
	public KonkaR3MmtMatch selectKonkaR3MmtMatchBySelf(KonkaR3MmtMatch t) {
		return (KonkaR3MmtMatch)super.getSqlMapClientTemplate().queryForObject("selectKonkaR3MmtMatchBySelf", t);
	}

	@Override
	public KonkaR3MmtMatch selectKonkaR3MmtMatchByR3ShopId(KonkaR3MmtMatch t) {
		return (KonkaR3MmtMatch)super.getSqlMapClientTemplate().queryForObject("selectKonkaR3MmtMatchByR3ShopId", t);
	}

}