package com.ebiz.mmt.dao.ibatis;
import java.util.HashMap;
import java.util.List;
import org.springframework.stereotype.Service;
import com.ebiz.mmt.dao.KonkaExpenseClaimsDao;
import com.ebiz.mmt.domain.KonkaExpenseClaims;
import com.ebiz.ssi.dao.ibatis.EntityDaoSqlMapImpl;

/**
 * Code by AutoGenerated Builder
 * AutoGenerated Builder Version 2.1
 * @author Hui,Gang
 * @datetime 2011-12-01 09:21:56
 */
@Service
public class KonkaExpenseClaimsDaoSqlMapImpl extends EntityDaoSqlMapImpl<KonkaExpenseClaims> implements KonkaExpenseClaimsDao {

	@SuppressWarnings("unchecked")
	public List<HashMap<String, String>> getKonkaExpenseClaimsCountList(
			KonkaExpenseClaims t) {
		return super.getSqlMapClientTemplate().queryForList(
				"selectKonkaExpenseClaimsCountList", t);
	}
	public Long getKonkaExpenseClaimsCountListCount(KonkaExpenseClaims t) {
		return (Long) super.getSqlMapClientTemplate().queryForObject(
				"selectKonkaExpenseClaimsCountListCount", t);
	}
}