package com.ebiz.mmt.dao.ibatis;

import org.springframework.stereotype.Repository;

import com.ebiz.ssi.dao.ibatis.EntityDaoSqlMapImpl;
import com.ebiz.mmt.dao.KonkaPePublicClickDao;
import com.ebiz.mmt.domain.KonkaPePublicClick;

/**
 * Code by AutoGenerated Builder
 * AutoGenerated Builder Version 2.1
 * @author Hui,Gang
 * @datetime 2011-10-11 20:14:30
 */
@Repository
public class KonkaPePublicClickDaoSqlMapImpl extends EntityDaoSqlMapImpl<KonkaPePublicClick> implements KonkaPePublicClickDao {

}