package com.ebiz.mmt.service.impl;

import java.util.HashMap;
import java.util.List;

import javax.annotation.Resource;

import org.springframework.stereotype.Service;

import com.ebiz.mmt.dao.KonkaPeAttachmentsDao;
import com.ebiz.mmt.domain.KonkaPeAttachments;
import com.ebiz.mmt.service.KonkaPeAttachmentsService;

/**
 * Code by AutoGenerated Builder
 * AutoGenerated Builder Version 2.1
 * @author Hui,Gang
 * @datetime 2011-09-29 16:08:30
 */
 @Service
public class KonkaPeAttachmentsServiceImpl implements KonkaPeAttachmentsService {
	
	@Resource
	private KonkaPeAttachmentsDao konkaPeAttachmentsDao;

	public Long createKonkaPeAttachments(KonkaPeAttachments t) {
		return this.konkaPeAttachmentsDao.insertEntity(t);
	}

	public KonkaPeAttachments getKonkaPeAttachments(KonkaPeAttachments t) {
		return this.konkaPeAttachmentsDao.selectEntity(t);
	}

	public Long getKonkaPeAttachmentsCount(KonkaPeAttachments t) {
		return this.konkaPeAttachmentsDao.selectEntityCount(t);
	}

	public List<KonkaPeAttachments> getKonkaPeAttachmentsList(KonkaPeAttachments t) {
		return this.konkaPeAttachmentsDao.selectEntityList(t);
	}

	public int modifyKonkaPeAttachments(KonkaPeAttachments t) {
		return this.konkaPeAttachmentsDao.updateEntity(t);
	}

	public int removeKonkaPeAttachments(KonkaPeAttachments t) {
		return this.konkaPeAttachmentsDao.deleteEntity(t);
	}

	public List<KonkaPeAttachments> getKonkaPeAttachmentsPaginatedList(KonkaPeAttachments t) {
		return this.konkaPeAttachmentsDao.selectEntityPaginatedList(t);
	}

	@Override
	public List<HashMap> getKonkaPeAttachmentsMap(KonkaPeAttachments t) {
		
		return this.konkaPeAttachmentsDao.selectKonkaPeAttachmentsMap(t);
	}	

}