package com.ebiz.mmt.service.impl;

import java.util.List;

import javax.annotation.Resource;

import org.apache.commons.lang.StringUtils;
import org.springframework.stereotype.Service;

import com.ebiz.mmt.dao.PePdModelDao;
import com.ebiz.mmt.dao.KonkaDeptPdLinkDao;
import com.ebiz.mmt.domain.KonkaDeptPdLink;
import com.ebiz.mmt.domain.PePdModel;
import com.ebiz.mmt.service.KonkaDeptPdLinkService;

/**
 * Code by AutoGenerated Builder
 * AutoGenerated Builder Version 2.1
 * @author Hui,Gang
 * @datetime 2011-10-10 17:03:48
 */
 @Service
public class KonkaDeptPdLinkServiceImpl implements KonkaDeptPdLinkService {
	
	@Resource
	private KonkaDeptPdLinkDao konkaDeptPdLinkDao;

	@Resource
	private PePdModelDao PePdModelDao;

	public Long createKonkaDeptPdLink(KonkaDeptPdLink t) {
		return this.konkaDeptPdLinkDao.insertEntity(t);
	}

	public KonkaDeptPdLink getKonkaDeptPdLink(KonkaDeptPdLink t) {
		return this.konkaDeptPdLinkDao.selectEntity(t);
	}

	public Long getKonkaDeptPdLinkCount(KonkaDeptPdLink t) {
		return this.konkaDeptPdLinkDao.selectEntityCount(t);
	}

	public List<KonkaDeptPdLink> getKonkaDeptPdLinkList(KonkaDeptPdLink t) {
		return this.konkaDeptPdLinkDao.selectEntityList(t);
	}

	public int modifyKonkaDeptPdLink(KonkaDeptPdLink t) {
		return this.konkaDeptPdLinkDao.updateEntity(t);
	}

	public int removeKonkaDeptPdLink(KonkaDeptPdLink t) {
		return this.konkaDeptPdLinkDao.deleteEntity(t);
	}

	public List<KonkaDeptPdLink> getKonkaDeptPdLinkPaginatedList(KonkaDeptPdLink t) {
		return this.konkaDeptPdLinkDao.selectEntityPaginatedList(t);
	}	
	/**
	 * @author  wangyang
	 * @param t
	 * @param pd_ids
	 * @return Long
	 * @datetime 2012-04-16 11:47:48
	 */
	public void createKonkaDeptPdLinkAndClean(KonkaDeptPdLink t,String pd_ids) {
		this.konkaDeptPdLinkDao.deleteEntity(t);
		if(StringUtils.isNotBlank(pd_ids)){
			String[] pd_id = pd_ids.split(",");
			for(int i=0;i<pd_id.length;i++){
				PePdModel model = new PePdModel();
				model.setPd_id(Long.valueOf(pd_id[i]));
				model = this.PePdModelDao.selectEntity(model);
				t.setPd_id(model.getPd_id());
				t.setCls_id(model.getCls_id());
				t.setPar_cls_id(model.getPar_cls_id());
				this.konkaDeptPdLinkDao.insertEntity(t);
			}
		}
	}
}