package com.ebiz.mmt.service.impl;

import java.util.Date;
import java.util.List;

import javax.annotation.Resource;

import org.apache.commons.validator.GenericValidator;
import org.springframework.stereotype.Service;

import com.ebiz.mmt.dao.KonkaR3MmtMatchDao;
import com.ebiz.mmt.dao.KonkaR3ShopDao;
import com.ebiz.mmt.domain.KonkaR3MmtMatch;
import com.ebiz.mmt.domain.KonkaR3Shop;
import com.ebiz.mmt.service.KonkaR3MmtMatchService;

/**
 * Code by AutoGenerated Builder
 * AutoGenerated Builder Version 2.1
 * @author Hui,Gang
 * @datetime 2011-09-24 14:50:49
 */
 @Service
public class KonkaR3MmtMatchServiceImpl implements KonkaR3MmtMatchService {
	
	 @Resource
	 private KonkaR3MmtMatchDao konkaR3MmtMatchDao;
	 @Resource
	 private KonkaR3ShopDao konkaR3ShopDao;

	public Long createKonkaR3MmtMatch(KonkaR3MmtMatch t) {
		return this.konkaR3MmtMatchDao.insertEntity(t);
	}

	public KonkaR3MmtMatch getKonkaR3MmtMatch(KonkaR3MmtMatch t) {
		return this.konkaR3MmtMatchDao.selectEntity(t);
	}

	public Long getKonkaR3MmtMatchCount(KonkaR3MmtMatch t) {
		return this.konkaR3MmtMatchDao.selectEntityCount(t);
	}

	public List<KonkaR3MmtMatch> getKonkaR3MmtMatchList(KonkaR3MmtMatch t) {
		return this.konkaR3MmtMatchDao.selectEntityList(t);
	}

	public int modifyKonkaR3MmtMatch(KonkaR3MmtMatch t) {
		return this.konkaR3MmtMatchDao.updateEntity(t);
	}

	public int removeKonkaR3MmtMatch(KonkaR3MmtMatch t) {
		return this.konkaR3MmtMatchDao.deleteEntity(t);
	}

	public List<KonkaR3MmtMatch> getKonkaR3MmtMatchPaginatedList(KonkaR3MmtMatch t) {
		return this.konkaR3MmtMatchDao.selectEntityPaginatedList(t);
	}
	
	public void match(String r3_shop_id,String mmt_shop_id,String mmt_shop_name){
		
		KonkaR3MmtMatch entity = new KonkaR3MmtMatch();
		
			if(GenericValidator.isLong(mmt_shop_id)){
				entity.setR3_shop_id(new Long(r3_shop_id));
				this.konkaR3MmtMatchDao.deleteEntity(entity);//先删除表里 此网点已经匹配过的记录
				
				entity.setMmt_shop_id(new Long(mmt_shop_id));
				entity.setMmt_shop_name(mmt_shop_name);
				entity.setMatch_date(new Date());
				this.createKonkaR3MmtMatch(entity);
			}
			KonkaR3Shop r3Shop = new KonkaR3Shop();
			r3Shop.setId(Long.valueOf(r3_shop_id));
			r3Shop.setIs_match(new Long(1));
			this.konkaR3ShopDao.updateEntity(r3Shop);
			
	}
	
	@Override
	public KonkaR3MmtMatch getKonkaR3MmtMatchBySelf(KonkaR3MmtMatch t) {
		return this.konkaR3MmtMatchDao.selectKonkaR3MmtMatchBySelf(t);
	}

	@Override
	public KonkaR3MmtMatch getKonkaR3MmtMatchByR3ShopId(KonkaR3MmtMatch t) {
		return this.konkaR3MmtMatchDao.selectKonkaR3MmtMatchByR3ShopId(t);
	}

}