package com.ebiz.mmt.service.impl;

import java.util.List;

import javax.annotation.Resource;

import org.springframework.stereotype.Service;

import com.ebiz.mmt.dao.KonkaPePublicScopeDao;
import com.ebiz.mmt.domain.KonkaPePublicScope;
import com.ebiz.mmt.service.KonkaPePublicScopeService;

/**
 * Code by AutoGenerated Builder
 * AutoGenerated Builder Version 2.1
 * @author Hui,Gang
 * @datetime 2011-10-11 19:37:19
 */
 @Service
public class KonkaPePublicScopeServiceImpl implements KonkaPePublicScopeService {
	
	@Resource
	private KonkaPePublicScopeDao konkaPePublicScopeDao;

	public Long createKonkaPePublicScope(KonkaPePublicScope t) {
		return this.konkaPePublicScopeDao.insertEntity(t);
	}

	public KonkaPePublicScope getKonkaPePublicScope(KonkaPePublicScope t) {
		return this.konkaPePublicScopeDao.selectEntity(t);
	}

	public Long getKonkaPePublicScopeCount(KonkaPePublicScope t) {
		return this.konkaPePublicScopeDao.selectEntityCount(t);
	}

	public List<KonkaPePublicScope> getKonkaPePublicScopeList(KonkaPePublicScope t) {
		return this.konkaPePublicScopeDao.selectEntityList(t);
	}

	public int modifyKonkaPePublicScope(KonkaPePublicScope t) {
		return this.konkaPePublicScopeDao.updateEntity(t);
	}

	public int removeKonkaPePublicScope(KonkaPePublicScope t) {
		return this.konkaPePublicScopeDao.deleteEntity(t);
	}

	public List<KonkaPePublicScope> getKonkaPePublicScopePaginatedList(KonkaPePublicScope t) {
		return this.konkaPePublicScopeDao.selectEntityPaginatedList(t);
	}	

}