package com.ebiz.mmt.service.impl;

import java.util.List;

import javax.annotation.Resource;

import org.springframework.stereotype.Service;

import com.ebiz.mmt.dao.KonkaPeArticleUserMsgDao;
import com.ebiz.mmt.domain.KonkaPeArticleUserMsg;
import com.ebiz.mmt.service.KonkaPeArticleUserMsgService;

/**
 * Code by AutoGenerated Builder
 * AutoGenerated Builder Version 2.1
 * @author Hui,Gang
 * @datetime 2011-09-29 16:08:29
 */
 @Service
public class KonkaPeArticleUserMsgServiceImpl implements KonkaPeArticleUserMsgService {
	
	@Resource
	private KonkaPeArticleUserMsgDao konkaPeArticleUserMsgDao;

	public Long createKonkaPeArticleUserMsg(KonkaPeArticleUserMsg t) {
		return this.konkaPeArticleUserMsgDao.insertEntity(t);
	}

	public KonkaPeArticleUserMsg getKonkaPeArticleUserMsg(KonkaPeArticleUserMsg t) {
		return this.konkaPeArticleUserMsgDao.selectEntity(t);
	}

	public Long getKonkaPeArticleUserMsgCount(KonkaPeArticleUserMsg t) {
		return this.konkaPeArticleUserMsgDao.selectEntityCount(t);
	}

	public List<KonkaPeArticleUserMsg> getKonkaPeArticleUserMsgList(KonkaPeArticleUserMsg t) {
		return this.konkaPeArticleUserMsgDao.selectEntityList(t);
	}

	public int modifyKonkaPeArticleUserMsg(KonkaPeArticleUserMsg t) {
		return this.konkaPeArticleUserMsgDao.updateEntity(t);
	}

	public int removeKonkaPeArticleUserMsg(KonkaPeArticleUserMsg t) {
		return this.konkaPeArticleUserMsgDao.deleteEntity(t);
	}

	public List<KonkaPeArticleUserMsg> getKonkaPeArticleUserMsgPaginatedList(KonkaPeArticleUserMsg t) {
		return this.konkaPeArticleUserMsgDao.selectEntityPaginatedList(t);
	}	

}