package com.ebiz.mmt.service.impl;

import java.util.List;

import javax.annotation.Resource;

import org.springframework.stereotype.Service;

import com.ebiz.mmt.dao.MmtEntpShopDao;
import com.ebiz.mmt.domain.MmtEntpShop;
import com.ebiz.mmt.service.MmtEntpShopService;

/**
 * Code by AutoGenerated Builder AutoGenerated Builder Version 2.1
 * 
 * @author Hui,Gang
 * @datetime 2011-09-29 15:54:30
 */
@Service
public class MmtEntpShopServiceImpl implements MmtEntpShopService {

	@Resource
	private MmtEntpShopDao mmtEntpShopDao;

	public Long createMmtEntpShop(MmtEntpShop t) {
		return this.mmtEntpShopDao.insertEntity(t);
	}

	public MmtEntpShop getMmtEntpShop(MmtEntpShop t) {
		return this.mmtEntpShopDao.selectEntity(t);
	}

	public Long getMmtEntpShopCount(MmtEntpShop t) {
		return this.mmtEntpShopDao.selectEntityCount(t);
	}

	public List<MmtEntpShop> getMmtEntpShopList(MmtEntpShop t) {
		return this.mmtEntpShopDao.selectEntityList(t);
	}

	public int modifyMmtEntpShop(MmtEntpShop t) {
		return this.mmtEntpShopDao.updateEntity(t);
	}

	public int removeMmtEntpShop(MmtEntpShop t) {
		return this.mmtEntpShopDao.deleteEntity(t);
	}

	public List<MmtEntpShop> getMmtEntpShopPaginatedList(MmtEntpShop t) {
		return this.mmtEntpShopDao.selectEntityPaginatedList(t);
	}

	public List<MmtEntpShop> getMmtEntpShopPaginatedListForSelect(MmtEntpShop t) {
		return this.mmtEntpShopDao.selectMmtEntpShopPaginatedListForSelect(t);
	}

	@Override
	public List<MmtEntpShop> getMmtEntpShopNotRepeatPaginatedList(MmtEntpShop t) {
		return this.mmtEntpShopDao.selectMmtEntpShopNotRepeatPaginatedList(t);
	}

	@Override
	public Long getMmtEntpShopNotRepeatCount(MmtEntpShop t) {
		return this.mmtEntpShopDao.selectMmtEntpShopNotRepeatCount(t);
	}

	public Long getMmtEntpShop2Count(MmtEntpShop t) {
		return this.mmtEntpShopDao.selectMmtEntpShop2Count(t);
	}

}