package com.ebiz.mmt.service;

import java.util.List;

import com.ebiz.mmt.domain.KonkaPePublicClick;

/**
 * Code by AutoGenerated Builder
 * AutoGenerated Builder Version 2.1
 * @author Hui,Gang
 * @datetime 2011-10-11 20:14:30
 */
public interface KonkaPePublicClickService {

	Long createKonkaPePublicClick(KonkaPePublicClick t);

	int modifyKonkaPePublicClick(KonkaPePublicClick t);

	int removeKonkaPePublicClick(KonkaPePublicClick t);

	KonkaPePublicClick getKonkaPePublicClick(KonkaPePublicClick t);

	List<KonkaPePublicClick> getKonkaPePublicClickList(KonkaPePublicClick t);

	Long getKonkaPePublicClickCount(KonkaPePublicClick t);

	List<KonkaPePublicClick> getKonkaPePublicClickPaginatedList(KonkaPePublicClick t);

}