package com.ebiz.mmt.domain;

import java.io.Serializable;
import java.util.Date;

import org.apache.commons.lang.builder.ReflectionToStringBuilder;
import org.apache.commons.lang.builder.ToStringStyle;

import com.ebiz.ssi.domain.BaseDomain;

/**
 * Code by AutoGenerated Builder
 * AutoGenerated Builder Version 2.1
 * @author Hui,Gang
 * @datetime 2011-10-11 20:14:29
 */
 public class KonkaPePublicClick extends BaseDomain implements Serializable {
 	
 	private static final long serialVersionUID = -1L;

	/**
	 * ID
	 */
    private Long id;
           
	/**
	 * 资讯ID
	 */
    private Long article_id;
           
	/**
	 * 网点ID
	 */
    private Long shop_id;
           
	/**
	 * 是否同意
0：不同意
1：同意
	 */
    private Long shop_agree;
           
	/**
	 * 最后次浏览时间
	 */
    private Date last_view_date;
           
	/**
	 * 浏览次数
	 */
    private Long view_count;
           
	public KonkaPePublicClick() {

	}
 
 	public void setId(Long id) {
		this.id = id;
	}
	
	public Long getId() {
		return id;
	}
           
 	public void setArticle_id(Long article_id) {
		this.article_id = article_id;
	}
	
	public Long getArticle_id() {
		return article_id;
	}
           
 	public void setShop_id(Long shop_id) {
		this.shop_id = shop_id;
	}
	
	public Long getShop_id() {
		return shop_id;
	}
           
 	public void setShop_agree(Long shop_agree) {
		this.shop_agree = shop_agree;
	}
	
	public Long getShop_agree() {
		return shop_agree;
	}
           
 	public void setLast_view_date(Date last_view_date) {
		this.last_view_date = last_view_date;
	}
	
	public Date getLast_view_date() {
		return last_view_date;
	}
           
 	public void setView_count(Long view_count) {
		this.view_count = view_count;
	}
	
	public Long getView_count() {
		return view_count;
	}
           
	@Override 
    public String toString() { 
   		return ReflectionToStringBuilder.toString(this, ToStringStyle.MULTI_LINE_STYLE);
    }
    
 }