package com.ebiz.mmt.dao.ibatis;

import org.springframework.stereotype.Repository;

import com.ebiz.ssi.dao.ibatis.EntityDaoSqlMapImpl;
import com.ebiz.mmt.dao.KonkaPePublicScopeDao;
import com.ebiz.mmt.domain.KonkaPePublicScope;

/**
 * Code by AutoGenerated Builder
 * AutoGenerated Builder Version 2.1
 * @author Hui,Gang
 * @datetime 2011-10-11 19:37:18
 */
@Repository
public class KonkaPePublicScopeDaoSqlMapImpl extends EntityDaoSqlMapImpl<KonkaPePublicScope> implements KonkaPePublicScopeDao {

}