package com.ebiz.mmt.service.impl;

import java.util.List;

import javax.annotation.Resource;

import org.springframework.stereotype.Service;

import com.ebiz.mmt.dao.KonkaPeArticleTypeDao;
import com.ebiz.mmt.domain.KonkaPeArticleType;
import com.ebiz.mmt.service.KonkaPeArticleTypeService;

/**
 * Code by AutoGenerated Builder
 * AutoGenerated Builder Version 2.1
 * @author Hui,Gang
 * @datetime 2011-09-28 18:29:21
 */
 @Service
public class KonkaPeArticleTypeServiceImpl implements KonkaPeArticleTypeService {
	
	@Resource
	private KonkaPeArticleTypeDao konkaPeArticleTypeDao;

	public Long createKonkaPeArticleType(KonkaPeArticleType t) {
		return this.konkaPeArticleTypeDao.insertEntity(t);
	}

	public KonkaPeArticleType getKonkaPeArticleType(KonkaPeArticleType t) {
		return this.konkaPeArticleTypeDao.selectEntity(t);
	}

	public Long getKonkaPeArticleTypeCount(KonkaPeArticleType t) {
		return this.konkaPeArticleTypeDao.selectEntityCount(t);
	}

	public List<KonkaPeArticleType> getKonkaPeArticleTypeList(KonkaPeArticleType t) {
		return this.konkaPeArticleTypeDao.selectEntityList(t);
	}

	public int modifyKonkaPeArticleType(KonkaPeArticleType t) {
		return this.konkaPeArticleTypeDao.updateEntity(t);
	}

	public int removeKonkaPeArticleType(KonkaPeArticleType t) {
		return this.konkaPeArticleTypeDao.deleteEntity(t);
	}

	public List<KonkaPeArticleType> getKonkaPeArticleTypePaginatedList(KonkaPeArticleType t) {
		return this.konkaPeArticleTypeDao.selectEntityPaginatedList(t);
	}	

}