package com.ebiz.mmt.dao.ibatis;

import java.util.List;

import org.springframework.dao.DataAccessException;
import org.springframework.stereotype.Repository;

import com.ebiz.mmt.dao.KonkaPeArticleInfoDao;
import com.ebiz.mmt.domain.KonkaPeArticleInfo;
import com.ebiz.ssi.dao.ibatis.EntityDaoSqlMapImpl;

/**
 * Code by AutoGenerated Builder AutoGenerated Builder Version 2.1
 * 
 * @author Hui,Gang
 * @datetime 2011-09-29 17:05:13
 */
@Repository
public class KonkaPeArticleInfoDaoSqlMapImpl extends EntityDaoSqlMapImpl<KonkaPeArticleInfo> implements
		KonkaPeArticleInfoDao {

	public Long selectKonkaPeArticleInfoCountForReceive(KonkaPeArticleInfo t) throws DataAccessException {
		return (Long) super.getSqlMapClientTemplate().queryForObject("selectKonkaPeArticleInfoCountForReceive", t);
	}

	@SuppressWarnings("unchecked")
	public List<KonkaPeArticleInfo> selectKonkaPeArticleInfoPaginatedListForReceive(KonkaPeArticleInfo t)
			throws DataAccessException {
		return super.getSqlMapClientTemplate().queryForList("selectKonkaPeArticleInfoPaginatedListForReceive", t);
	}

	/**
	 * @author Hu,Hao
	 * @version 2013-05-30
	 */
	@SuppressWarnings("unchecked")
	public List<KonkaPeArticleInfo> selectKonkaPeArticleInfoForMobilePaginatedList(KonkaPeArticleInfo t)
			throws DataAccessException {
		return super.getSqlMapClientTemplate().queryForList("selectKonkaPeArticleInfoForMobilePaginatedList", t);
	}

	/**
	 * @author Hu,Hao
	 * @version 2013-05-30
	 */
	public Long selectKonkaPeArticleInfoForMobileCount(KonkaPeArticleInfo t) {
		return (Long) super.getSqlMapClientTemplate().queryForObject("selectKonkaPeArticleInfoForMobileCount", t);
	}

	/**
	 * @author Hu,Hao
	 * @version 2013-07-14
	 */
	@SuppressWarnings("unchecked")
	public List<KonkaPeArticleInfo> selectKonkaPeArticleInfoForGroupPaginatedList(KonkaPeArticleInfo t) {
		return super.getSqlMapClientTemplate().queryForList("selectKonkaPeArticleInfoForGroupPaginatedList", t);
	}
}